# KNESER NEY - IZGLAĐIVANJE KOD MODELIRANJA JEZIKA
## Ivona Mustapić-Jogun

# 1. Korpusi

Za korpus sam odabrala Preobrazbu od Franza Kafke. Duljina korpusa je 119148.

In [1]:
korpus=open("korpus.txt", "r").read()
len(korpus)

119148

Omjer korpusa za treniranje i korpusa za testiranje je otprilike 3:1 (otprilike je zato što nisam htjela prekinuti 
rečenicu na pola). Duljina korpusa za treniranje je 88036, a korpusa za testiranje 29218.

In [21]:
korpus_za_treniranje=korpus[0:int(len(korpus)*0.75)+95]
len(korpus_za_treniranje)

88036

In [22]:
korpus_za_testiranje=korpus[int(len(korpus)*0.75)+96:]
len(korpus_za_testiranje)


29218

Izbacila sam znakove nepotrebne za našu analizu iz svih korpusa.

In [4]:
for i in korpus:
    if i == ',' or i=='"' or i==';' or i==":":
        korpus=korpus.replace(i,'')
for i in range(0, len(korpus)-3):
    if korpus[i:i+3]==' - ':
        korpus=korpus.replace(korpus[i:i+3],' ')
for i in range(0, len(korpus)-2):
    if korpus[i:i+2]==' -':
        korpus=korpus.replace(korpus[i:i+2],' ')
for i in range(0, len(korpus)-2):
    if korpus[i:i+2]=='- ':
        korpus=korpus.replace(korpus[i:i+2],' ')

In [5]:
for i in korpus_za_treniranje:
    if i == ',' or i=='"' or i==';' or i==":":
        korpus_za_treniranje=korpus_za_treniranje.replace(i,'')
for i in range(0, len(korpus_za_treniranje)-3):
    if korpus_za_treniranje[i:i+3]==' - ':
        korpus_za_treniranje=korpus_za_treniranje.replace(korpus_za_treniranje[i:i+3],' ')
for i in range(0, len(korpus_za_treniranje)-2):
    if korpus_za_treniranje[i:i+2]==' -':
        korpus_za_treniranje=korpus_za_treniranje.replace(korpus_za_treniranje[i:i+2],' ')
for i in range(0, len(korpus_za_treniranje)-2):
    if korpus_za_treniranje[i:i+2]=='- ':
        korpus_za_treniranje=korpus_za_treniranje.replace(korpus_za_treniranje[i:i+2],' ')

In [6]:
for i in korpus_za_testiranje:
    if i == ',' or i=='"' or i==';' or i==":":
        korpus_za_testiranje=korpus_za_testiranje.replace(i,'')
for i in range(0, len(korpus_za_testiranje)-3):
    if korpus_za_testiranje[i:i+3]==' - ':
        korpus_za_testiranje=korpus_za_testiranje.replace(korpus_za_testiranje[i:i+3],' ')
for i in range(0, len(korpus_za_testiranje)-2):
    if korpus_za_testiranje[i:i+2]==' -':
        korpus_za_testiranje=korpus_za_testiranje.replace(korpus_za_testiranje[i:i+2],' ')
for i in range(0, len(korpus_za_testiranje)-2):
    if korpus_za_testiranje[i:i+2]=='- ':
        korpus_za_testiranje=korpus_za_testiranje.replace(korpus_za_testiranje[i:i+2],' ')

## 1.1. Analiza korpusa

## 1.1.1. Analiza korpusa bez stemiranja

U ovom dijelu napravila sam analizu unigrama, bigrama i trigrama korpusa bez stemiranja. Prvo sam stvorila listu rečenica koje se sastoje od n-grama, zatim sam stvorila rječnik kojem su ključevi n-grami, a vrijednosti broj pojavljivanja u korpusu i nakon toga sam sortirala rječnik u padajućem poretku.

### Unigrami

Broj unigrama u korpusu je 22007 (broj riječi), a broj različitih unigrama je 2771 (broj pojavnica).

In [7]:
recenice_unigrama=[]
recenica=''
for i in range(0,len(korpus)):
    if (korpus[i]=='.' and korpus[i-2:i]!="Mr" and korpus[i-3:i]!="Mrs") or korpus[i]=='!' or korpus[i]=='?':
        recenice_unigrama.append(recenica.split())
        recenica=''
    else:
        recenica=recenica+korpus[i]
br=0
for i in recenice_unigrama:
    for j in i:
        br=br+1
print(br)

22007


In [470]:
rjecnik_unigrama={}
for recenica in recenice_unigrama:
    for rijec in recenica:
        if rijec not in rjecnik_unigrama:
            rjecnik_unigrama[rijec]=1
        else:
            rjecnik_unigrama[rijec]+=1
print(len(rjecnik_unigrama))

2771


Unigram koji se najviše puta pojavljuje je 'the' i to 1096 puta.

In [471]:
for unigram in sorted(rjecnik_unigrama.items(), key=lambda item: item[1], reverse=True):
    print(unigram)

('the', 1096)
('to', 753)
('and', 612)
('his', 524)
('he', 494)
('of', 429)
('was', 406)
('had', 350)
('in', 338)
('that', 324)
('it', 316)
('a', 283)
('as', 232)
('Gregor', 199)
('with', 194)
('him', 188)
('would', 184)
('her', 183)
('not', 176)
('she', 172)
('at', 158)
('for', 158)
('on', 147)
('but', 139)
('they', 135)
('room', 131)
('all', 129)
('could', 119)
('be', 118)
('from', 116)
('out', 113)
('have', 107)
('been', 101)
("Gregor's", 99)
('sister', 96)
('there', 95)
('father', 93)
('himself', 87)
('if', 87)
('door', 87)
('so', 83)
('He', 82)
('back', 82)
('up', 81)
('this', 79)
('mother', 79)
('into', 78)
('even', 78)
('now', 76)
('more', 71)
('did', 71)
('then', 70)
('their', 68)
('were', 66)
('about', 65)
('them', 64)
('way', 62)
('when', 61)
('time', 59)
('only', 58)
('I', 57)
('what', 56)
('no', 56)
('than', 55)
('by', 53)
('The', 51)
('said', 51)
('one', 50)
('little', 49)
('any', 47)
('you', 46)
('just', 46)
('get', 44)
('still', 44)
('do', 43)
('first', 42)
('other', 42)

('dry', 1)
('roll', 1)
('butter', 1)
('salt', 1)
('poured', 1)
('feelings', 1)
('whirred', 1)
('healed', 1)
('knife', 1)
('yesterday', 1)
('Am', 1)
('sucking', 1)
('greedily', 1)
('compellingly', 1)
('attracted', 1)
('Quickly', 1)
('watering', 1)
('consumed', 1)
('Long', 1)
('lethargic', 1)
('withdraw', 1)
('self-control', 1)
('rounded', 1)
('Half', 1)
('bulging', 1)
('unselfconsciously', 1)
('swept', 1)
('left-overs', 1)
('mixing', 1)
('dropped', 1)
('bin', 1)
('lid', 1)
('second', 1)
('errand', 1)
('starve', 1)
('feeding', 1)
('suffering', 1)
('content', 1)
('sighs', 1)
('saints', 1)
('construed', 1)
('enjoyed', 1)
('diligently', 1)
('sadly', 1)
("everything's", 1)
('scurry', 1)
('appropriate', 1)
('press', 1)
('seldom', 1)
('mealtime', 1)
('subject', 1)
('knees', 1)
('begged', 1)
('within', 1)
('tearfully', 1)
('thanking', 1)
('dismissal', 1)
('swore', 1)
('emphatically', 1)
('cooking', 1)
('bother', 1)
('unsuccessfully', 1)
('similar', 1)
('drank', 1)
('beer', 1)
('hoping', 1)
('ad

### Bigrami

Broj bigrama u korpusu je 21208, a broj različitih bigrama je 12733.

In [401]:
recenice_bigrama=[]
recenica=[]
for i in recenice_unigrama:
    for j in range(0,len(i)-1):
        recenica.append(i[j]+" "+i[j+1])
    recenice_bigrama.append(recenica)
    recenica=[]
br=0
for i in recenice_bigrama:
    for j in i:
        br=br+1
print(br)

21208


In [402]:
rjecnik_bigrama={}
for recenica in recenice_bigrama:
    for rijec in recenica:
        if rijec not in rjecnik_bigrama:
            rjecnik_bigrama[rijec]=1
        else:
            rjecnik_bigrama[rijec]+=1
print(len(rjecnik_bigrama))

12733


Bigram koji se najviše puta pojavljuje je 'of the' i to 96 puta.

In [403]:
for bigram in sorted(rjecnik_bigrama.items(), key=lambda item: item[1], reverse=True):
    print(bigram)

('of the', 96)
('in the', 86)
('he had', 82)
('the door', 73)
('he was', 67)
('it was', 64)
('to the', 63)
('his sister', 63)
('had been', 54)
('he could', 53)
('on the', 53)
('his father', 53)
('that he', 52)
('as he', 45)
('of his', 43)
('as if', 42)
('to be', 41)
('at the', 40)
('from the', 40)
('in his', 39)
('the room', 37)
('into the', 35)
('did not', 34)
('the chief', 34)
('chief clerk', 34)
('out of', 33)
('and the', 33)
('he would', 33)
('his mother', 33)
('all the', 32)
('she had', 32)
('if he', 31)
('his head', 31)
('to him', 31)
('to get', 30)
('would have', 30)
('with his', 30)
('was not', 30)
('his room', 30)
('with the', 29)
('a little', 28)
('to do', 28)
('so that', 28)
('had to', 28)
('they had', 28)
('to his', 27)
('and he', 26)
('have to', 25)
('on his', 24)
("Gregor's father", 24)
('able to', 23)
('with a', 23)
('when he', 23)
('It was', 23)
('at all', 23)
('wanted to', 23)
('of it', 23)
('Gregor had', 22)
('there was', 22)
('could not', 22)
('had not', 21)
('the ot

('making him', 2)
('go for', 2)
('contrast with', 2)
('father called', 2)
('get a', 2)
('ran out', 2)
('shut again', 2)
('again they', 2)
('Gregor in', 2)
('become much', 2)
('So they', 2)
('although they', 2)
('clear enough', 2)
('become used', 2)
('though that', 2)
('and were', 2)
('and from', 2)
('doctor and', 2)
('not really', 2)
('was said', 2)
('make his', 2)
('voice as', 2)
('as even', 2)
('even this', 2)
('different from', 2)
('very quiet', 2)
('sat at', 2)
('and listening', 2)
('pushed his', 2)
('door with', 2)
('Once there', 2)
('and threw', 2)
('holding himself', 2)
('upright against', 2)
('using the', 2)
('the adhesive', 2)
('turning the', 2)
('lock with', 2)
('seemed unfortunately', 2)
('unfortunately to', 2)
('a very', 2)
('this but', 2)
('they should', 2)
('his efforts', 2)
('around the', 2)
('pushed it', 2)
('lock as', 2)
("was Gregor's", 2)
('sign that', 2)
('breath he', 2)
('door in', 2)
('before he', 2)
('first to', 2)
('turn himself', 2)
('the double', 2)
('double d

('a cautious', 1)
('cautious knock', 1)
('knock at', 1)
('door near', 1)
('near his', 1)
('Gregor somebody', 1)
('somebody called', 1)
('called it', 1)
("mother it's", 1)
("it's quarter", 1)
("Didn't you", 1)
('go somewhere', 1)
('That gentle', 1)
('gentle voice', 1)
('was shocked', 1)
('shocked when', 1)
('own voice', 1)
('voice answering', 1)
('answering it', 1)
('hardly be', 1)
('be recognised', 1)
('recognised as', 1)
('voice he', 1)
('had before', 1)
('As if', 1)
('if from', 1)
('from deep', 1)
('deep inside', 1)
('inside him', 1)
('him there', 1)
('painful and', 1)
('and uncontrollable', 1)
('uncontrollable squeaking', 1)
('squeaking mixed', 1)
('words could', 1)
('made out', 1)
('then there', 1)
('a sort', 1)
('of echo', 1)
('echo which', 1)
('made them', 1)
('them unclear', 1)
('unclear leaving', 1)
('the hearer', 1)
('hearer unsure', 1)
('unsure whether', 1)
('had heard', 1)
('heard properly', 1)
('properly or', 1)
('or not', 1)
('give a', 1)
('a full', 1)
('full answer', 1)
(

("mother's screams", 1)
('called into', 1)
('kitchen through', 1)
('hall clapping', 1)
('clapping his', 1)
('hands get', 1)
('a locksmith', 1)
('locksmith here', 1)
('here now', 1)
('two girls', 1)
('girls their', 1)
('their skirts', 1)
('skirts swishing', 1)
('swishing immediately', 1)
('immediately ran', 1)
('out through', 1)
('hall wrenching', 1)
('wrenching open', 1)
('flat as', 1)
('How had', 1)
('sister managed', 1)
('dressed so', 1)
('so quickly', 1)
('no sound', 1)
('door banging', 1)
('banging shut', 1)
('have left', 1)
('it open', 1)
('open people', 1)
('people often', 1)
('often do', 1)
('do in', 1)
('in homes', 1)
('homes where', 1)
('where something', 1)
('something awful', 1)
('awful has', 1)
('has happened', 1)
('contrast had', 1)
('much calmer', 1)
("they couldn't", 1)
("couldn't understand", 1)
('understand his', 1)
('his words', 1)
('words any', 1)
('more although', 1)
('they seemed', 1)
('seemed clear', 1)
('him clearer', 1)
('clearer than', 1)
('before perhaps', 1)


('what now', 1)
('now if', 1)
('if all', 1)
('this peace', 1)
('and wealth', 1)
('wealth and', 1)
('and comfort', 1)
('comfort should', 1)
('should come', 1)
('horrible and', 1)
('and frightening', 1)
('frightening end', 1)
('about too', 1)
('too much', 1)
('much so', 1)
('about crawling', 1)
('Once during', 1)
('during that', 1)
('that long', 1)
('long evening', 1)
('evening the', 1)
('opened very', 1)
('very slightly', 1)
('slightly and', 1)
('and hurriedly', 1)
('hurriedly closed', 1)
('closed again', 1)
('again later', 1)
('side did', 1)
('same it', 1)
('seemed that', 1)
('that someone', 1)
('someone needed', 1)
('to enter', 1)
('enter the', 1)
('but thought', 1)
('thought better', 1)
('went and', 1)
('waited immediately', 1)
('immediately by', 1)
('door resolved', 1)
('resolved either', 1)
('either to', 1)
('bring the', 1)
('the timorous', 1)
('timorous visitor', 1)
('visitor into', 1)
('way or', 1)
('least to', 1)
('out who', 1)
('opened no', 1)
('that night', 1)
('night and', 1)

('pleasure for', 1)
('to cut', 1)
('cut himself', 1)
('off so', 1)
('so completely', 1)
('She left', 1)
('sheet where', 1)
('he glimpsed', 1)
('glimpsed a', 1)
('of gratitude', 1)
('gratitude one', 1)
('one time', 1)
('he carefully', 1)
('carefully looked', 1)
('sheet to', 1)
('see how', 1)
('sister liked', 1)
('liked the', 1)
('new arrangement', 1)
('first fourteen', 1)
('fourteen days', 1)
("days Gregor's", 1)
("Gregor's parents", 1)
('parents could', 1)
('bring themselves', 1)
('themselves to', 1)
('often hear', 1)
('hear them', 1)
('them say', 1)
('say how', 1)
('they appreciated', 1)
('appreciated all', 1)
('new work', 1)
('work his', 1)
('doing even', 1)
('though before', 1)
('had seen', 1)
('seen her', 1)
('a girl', 1)
('girl who', 1)
('was somewhat', 1)
('somewhat useless', 1)
('useless and', 1)
('and frequently', 1)
('frequently been', 1)
('been annoyed', 1)
('annoyed with', 1)
('two of', 1)
('them father', 1)
('often both', 1)
('both wait', 1)
('wait outside', 1)
('room while

('hours before', 1)
('before it', 1)
('then lying', 1)
('seen from', 1)
('room he', 1)
('family in', 1)
('light of', 1)
('and listen', 1)
('their conversation', 1)
("with everyone's", 1)
("everyone's permission", 1)
('permission in', 1)
('and thus', 1)
('thus quite', 1)
('quite differently', 1)
('differently from', 1)
('from before', 1)
('They no', 1)
('longer held', 1)
('held the', 1)
('the lively', 1)
('lively conversations', 1)
('conversations of', 1)
('of earlier', 1)
('earlier times', 1)
('times of', 1)
('the ones', 1)
('ones that', 1)
('Gregor always', 1)
('always thought', 1)
('about with', 1)
('with longing', 1)
('longing when', 1)
('was tired', 1)
('and getting', 1)
('getting into', 1)
('the damp', 1)
('damp bed', 1)
('some small', 1)
('small hotel', 1)
('hotel room', 1)
('were usually', 1)
('usually very', 1)
('quiet nowadays', 1)
('Soon after', 1)
('after dinner', 1)
('dinner his', 1)
('chair his', 1)
('would urge', 1)
('urge each', 1)
('other to', 1)
('be quiet', 1)
('quiet

('block their', 1)
('their view', 1)
('did become', 1)
('little annoyed', 1)
('not clear', 1)
('clear whether', 1)
("father's behaviour", 1)
('behaviour that', 1)
('that annoyed', 1)
('annoyed them', 1)
('the dawning', 1)
('dawning realisation', 1)
('realisation that', 1)
('a neighbour', 1)
('neighbour like', 1)
('like Gregor', 1)
('They asked', 1)
("asked Gregor's", 1)
('father for', 1)
('for explanations', 1)
('explanations raised', 1)
('raised their', 1)
('arms like', 1)
('had tugged', 1)
('tugged excitedly', 1)
('excitedly at', 1)
('at their', 1)
('beards and', 1)
('moved back', 1)
('towards their', 1)
('room only', 1)
('only very', 1)
("Meanwhile Gregor's", 1)
('had overcome', 1)
('the despair', 1)
('despair she', 1)
('fallen into', 1)
('into when', 1)
('when her', 1)
('playing was', 1)
('suddenly interrupted', 1)
('had let', 1)
('hands drop', 1)
('drop and', 1)
('and let', 1)
('let violin', 1)
('violin and', 1)
('and bow', 1)
('bow hang', 1)
('hang limply', 1)
('limply for', 1)
(

### Trigrami

Broj trigrama u korpusu je 20420, a broj različitih trigrama je 18385.

In [404]:
recenice_trigrama=[]
recenica=[]
for i in recenice_unigrama:
    for j in range(0,len(i)-2):
        recenica.append(i[j]+" "+i[j+1]+" "+i[j+2])
    recenice_trigrama.append(recenica)
    recenica=[]
br=0
for i in recenice_trigrama:
    for j in i:
        br=br+1
print(br)

20420


In [405]:
rjecnik_trigrama={}
for recenica in recenice_trigrama:
    for rijec in recenica:
        if rijec not in rjecnik_trigrama:
            rjecnik_trigrama[rijec]=1
        else:
            rjecnik_trigrama[rijec]+=1
print(len(rjecnik_trigrama))

18385


Trigram koji se najviše puta pojavljuje je 'the chief clerk' i to 31 puta. Ovime vidimo da iako se 'the' pojavljuje kao najčešći unigram i kao riječ u najčešćem bigramu, ipak nije riječ najčešćeg trigrama.

In [406]:
for trigram in sorted(rjecnik_trigrama.items(), key=lambda item: item[1], reverse=True):
    print(trigram)

('the chief clerk', 31)
('the living room', 15)
('out of the', 13)
('he had been', 13)
('the three gentlemen', 12)
('the door and', 11)
('that he had', 10)
('that he could', 10)
('of his body', 10)
('as if he', 10)
('in front of', 10)
('so that he', 9)
('chest of drawers', 9)
('he would have', 9)
('would have been', 9)
('one of the', 9)
('he had to', 9)
('that he was', 9)
('on the floor', 9)
('under the couch', 9)
('mother and sister', 9)
('would have to', 8)
('he did not', 8)
('open the door', 8)
('for him to', 8)
('to the door', 8)
('into his room', 8)
('that they had', 8)
('on his back', 7)
('that it was', 7)
('of the bed', 7)
('he wanted to', 7)
('he could not', 7)
('the door of', 7)
('in the morning', 7)
('in his room', 7)
('to open the', 7)
('on the other', 7)
('over to the', 7)
('and he was', 7)
('the next room', 7)
('the door to', 7)
('to his father', 7)
('and it was', 7)
('where he was', 6)
('back into his', 6)
('the chest of', 6)
('that he would', 6)
('at the door', 6)
('coul

('have put in', 1)
('put in his', 1)
('in his report', 1)
('his report about', 1)
("report about Gregor's", 1)
("about Gregor's not", 1)
("Gregor's not being", 1)
('not being there', 1)
('being there a', 1)
('there a long', 1)
('The office assistant', 1)
('office assistant was', 1)
('assistant was the', 1)
("was the boss's", 1)
("the boss's man", 1)
("boss's man spineless", 1)
('man spineless and', 1)
('spineless and with', 1)
('and with no', 1)
('with no understanding', 1)
('What about if', 1)
('about if he', 1)
('if he reported', 1)
('he reported sick', 1)
('But that would', 1)
('would be extremely', 1)
('be extremely strained', 1)
('extremely strained and', 1)
('strained and suspicious', 1)
('and suspicious as', 1)
('suspicious as in', 1)
('as in fifteen', 1)
('in fifteen years', 1)
('fifteen years of', 1)
('years of service', 1)
('of service Gregor', 1)
('service Gregor had', 1)
('had never once', 1)
('never once yet', 1)
('once yet been', 1)
('yet been ill', 1)
('His boss would', 

('from the room', 1)
('to his left', 1)
('his left the', 1)
('left the chief', 1)
('chief clerk has', 1)
('clerk has come', 1)
('has come round', 1)
('come round and', 1)
('round and wants', 1)
('and wants to', 1)
('wants to know', 1)
('to know why', 1)
('know why you', 1)
("why you didn't", 1)
("you didn't leave", 1)
("didn't leave on", 1)
('leave on the', 1)
('on the early', 1)
('the early train', 1)
("We don't know", 1)
("don't know what", 1)
('what to say', 1)
('to say to', 1)
('say to him', 1)
('And anyway he', 1)
('anyway he wants', 1)
('he wants to', 1)
('wants to speak', 1)
('speak to you', 1)
('to you personally', 1)
('So please open', 1)
('please open up', 1)
('open up this', 1)
('up this door', 1)
("I'm sure he'll", 1)
("sure he'll be", 1)
("he'll be good", 1)
('be good enough', 1)
('good enough to', 1)
('enough to forgive', 1)
('to forgive the', 1)
('forgive the untidiness', 1)
('the untidiness of', 1)
('untidiness of your', 1)
('of your room', 1)
('Then the chief', 1)
('ch

('handle of the', 1)
('door to open', 1)
('to open it', 1)
('open it completely', 1)
('Because he had', 1)
('had to open', 1)
('the door in', 1)
('door in this', 1)
('this way it', 1)
('it was already', 1)
('was already wide', 1)
('already wide open', 1)
('wide open before', 1)
('open before he', 1)
('before he could', 1)
('He had first', 1)
('had first to', 1)
('first to slowly', 1)
('to slowly turn', 1)
('slowly turn himself', 1)
('turn himself around', 1)
('himself around one', 1)
('around one of', 1)
('double doors and', 1)
('doors and he', 1)
('and he had', 1)
('do it very', 1)
('it very carefully', 1)
('very carefully if', 1)
('carefully if he', 1)
('want to fall', 1)
('to fall flat', 1)
('fall flat on', 1)
('flat on his', 1)
('his back before', 1)
('back before entering', 1)
('before entering the', 1)
('was still occupied', 1)
('still occupied with', 1)
('occupied with this', 1)
('with this difficult', 1)
('this difficult movement', 1)
('difficult movement unable', 1)
('movement

('his father was', 1)
('father was able', 1)
('see his good', 1)
('his good intentions', 1)
('intentions as he', 1)
('he did nothing', 1)
('did nothing to', 1)
('nothing to hinder', 1)
('to hinder him', 1)
('hinder him in', 1)
('him in fact', 1)
('in fact now', 1)
('fact now and', 1)
('then he used', 1)
('he used the', 1)
('used the tip', 1)
('the tip of', 1)
('tip of his', 1)
('of his stick', 1)
('his stick to', 1)
('stick to give', 1)
('to give directions', 1)
('give directions from', 1)
('directions from a', 1)
('from a distance', 1)
('a distance as', 1)
('distance as to', 1)
('as to which', 1)
('to which way', 1)
('which way to', 1)
('way to turn', 1)
('only his father', 1)
('father would stop', 1)
('would stop that', 1)
('stop that unbearable', 1)
('that unbearable hissing', 1)
('It was making', 1)
('was making Gregor', 1)
('making Gregor quite', 1)
('Gregor quite confused', 1)
('When he had', 1)
('he had nearly', 1)
('had nearly finished', 1)
('nearly finished turning', 1)
('turn

('the room as', 1)
('room as eating', 1)
('as eating so', 1)
('eating so much', 1)
('so much food', 1)
('much food had', 1)
('food had rounded', 1)
('had rounded out', 1)
('rounded out his', 1)
('out his body', 1)
('his body a', 1)
('body a little', 1)
('could hardly breathe', 1)
('hardly breathe in', 1)
('breathe in that', 1)
('in that narrow', 1)
('that narrow space', 1)
('Half suffocating he', 1)
('suffocating he watched', 1)
('he watched with', 1)
('watched with bulging', 1)
('with bulging eyes', 1)
('bulging eyes as', 1)
('eyes as his', 1)
('as his sister', 1)
('his sister unselfconsciously', 1)
('sister unselfconsciously took', 1)
('unselfconsciously took a', 1)
('took a broom', 1)
('a broom and', 1)
('broom and swept', 1)
('and swept up', 1)
('swept up the', 1)
('up the left-overs', 1)
('the left-overs mixing', 1)
('left-overs mixing them', 1)
('mixing them in', 1)
('them in with', 1)
('with the food', 1)
('food he had', 1)
('not even touched', 1)
('even touched at', 1)
('touche

('immediately open the', 1)
('open the window', 1)
('window while he', 1)
('while he was', 1)
('he was still', 1)
('still there but', 1)
('there but not', 1)
('but not only', 1)
('only did she', 1)
('did she not', 1)
('she not come', 1)
('not come in', 1)
('come in she', 1)
('in she went', 1)
('she went straight', 1)
('went straight back', 1)
('straight back and', 1)
('back and closed', 1)
('and closed the', 1)
('closed the door', 1)
('the door behind', 1)
('door behind her', 1)
('behind her a', 1)
('her a stranger', 1)
('a stranger would', 1)
('stranger would have', 1)
('would have thought', 1)
('have thought he', 1)
('thought he had', 1)
('he had threatened', 1)
('had threatened her', 1)
('threatened her and', 1)
('her and tried', 1)
('and tried to', 1)
('tried to bite', 1)
('to bite her', 1)
('Gregor went straight', 1)
('went straight to', 1)
('straight to hide', 1)
('to hide himself', 1)
('hide himself under', 1)
('himself under the', 1)
('the couch of', 1)
('couch of course', 1)
(

('other room catching', 1)
('room catching their', 1)
('catching their breath', 1)
('their breath he', 1)
('breath he sallied', 1)
('he sallied out', 1)
('sallied out changed', 1)
('out changed direction', 1)
('changed direction four', 1)
('direction four times', 1)
('four times not', 1)
('times not knowing', 1)
('not knowing what', 1)
('what he should', 1)
('he should save', 1)
('should save first', 1)
('save first before', 1)
('first before his', 1)
('before his attention', 1)
('his attention was', 1)
('attention was suddenly', 1)
('was suddenly caught', 1)
('suddenly caught by', 1)
('caught by the', 1)
('by the picture', 1)
('the picture on', 1)
('picture on the', 1)
('the wall which', 1)
('wall which was', 1)
('which was already', 1)
('was already denuded', 1)
('already denuded of', 1)
('denuded of everything', 1)
('of everything else', 1)
('everything else that', 1)
('else that had', 1)
('had been on', 1)
('been on it', 1)
('on it of', 1)
('it of the', 1)
('of the lady', 1)
('the 

('father would slumber', 1)
('would slumber where', 1)
('slumber where he', 1)
('he was fully', 1)
('as if always', 1)
('if always ready', 1)
('always ready to', 1)
('ready to serve', 1)
('to serve and', 1)
('serve and expecting', 1)
('and expecting to', 1)
('expecting to hear', 1)
('hear the voice', 1)
('of his superior', 1)
('his superior even', 1)
('superior even here', 1)
('The uniform had', 1)
('uniform had not', 1)
('not been new', 1)
('been new to', 1)
('new to start', 1)
('to start with', 1)
('start with but', 1)
('with but as', 1)
('as a result', 1)
('a result of', 1)
('result of this', 1)
('of this it', 1)
('this it slowly', 1)
('it slowly became', 1)
('slowly became even', 1)
('became even shabbier', 1)
('even shabbier despite', 1)
('shabbier despite the', 1)
('despite the efforts', 1)
('the efforts of', 1)
("efforts of Gregor's", 1)
("of Gregor's mother", 1)
('sister to look', 1)
('Gregor would often', 1)
('would often spend', 1)
('often spend the', 1)
('spend the whole', 1

('were left where', 1)
('left where they', 1)
('where they landed', 1)
('they landed when', 1)
('landed when they', 1)
('when they had', 1)
('they had first', 1)
('first been thrown', 1)
('been thrown unless', 1)
('thrown unless Gregor', 1)
('unless Gregor made', 1)
('Gregor made his', 1)
('his way through', 1)
('way through the', 1)
('through the junk', 1)
('the junk and', 1)
('junk and moved', 1)
('and moved it', 1)
('moved it somewhere', 1)
('it somewhere else', 1)
('first he moved', 1)
('he moved it', 1)
('moved it because', 1)
('it because with', 1)
('because with no', 1)
('with no other', 1)
('no other room', 1)
('other room free', 1)
('room free where', 1)
('free where he', 1)
('he could crawl', 1)
('could crawl about', 1)
('about he was', 1)
('forced to but', 1)
('to but later', 1)
('but later on', 1)
('later on he', 1)
('on he came', 1)
('he came to', 1)
('came to enjoy', 1)
('to enjoy it', 1)
('enjoy it although', 1)
('it although moving', 1)
('although moving about', 1)
('mo

('father some more', 1)
('some more definite', 1)
('more definite ideas', 1)
('He sat upright', 1)
('sat upright played', 1)
('upright played with', 1)
('played with his', 1)
('with his uniform', 1)
('his uniform cap', 1)
('uniform cap between', 1)
('cap between the', 1)
('between the plates', 1)
('the plates left', 1)
('plates left by', 1)
('left by the', 1)
('by the three', 1)
('three gentlemen after', 1)
('gentlemen after their', 1)
('after their meal', 1)
('their meal and', 1)
('meal and occasionally', 1)
('and occasionally looked', 1)
('occasionally looked down', 1)
('looked down at', 1)
('down at Gregor', 1)
('lay there immobile', 1)
('We have to', 1)
('of it said', 1)
("it said Gregor's", 1)
("said Gregor's sister", 1)
("Gregor's sister now", 1)
('sister now speaking', 1)
('now speaking only', 1)
('speaking only to', 1)
('only to her', 1)
('to her father', 1)
('her father as', 1)
('father as her', 1)
('as her mother', 1)
('mother was too', 1)
('was too occupied', 1)
('too occupi

('excusal Mr. Samsa', 1)
('Mr. Samsa to', 1)
('Samsa to his', 1)
('to his employers', 1)
('his employers Mrs.', 1)
('employers Mrs. Samsa', 1)
('Mrs. Samsa to', 1)
('Samsa to her', 1)
('to her contractor', 1)
('her contractor and', 1)
('contractor and Grete', 1)
('and Grete to', 1)
('Grete to her', 1)
('to her principal', 1)
('The cleaner came', 1)
('came in while', 1)
('in while they', 1)
('were writing to', 1)
('writing to tell', 1)
('tell them she', 1)
('them she was', 1)
('she was going', 1)
("was going she'd", 1)
("going she'd finished", 1)
("she'd finished her", 1)
('finished her work', 1)
('her work for', 1)
('work for that', 1)
('for that morning', 1)
('The three of', 1)
('of them at', 1)
('them at first', 1)
('at first just', 1)
('first just nodded', 1)
('just nodded without', 1)
('nodded without looking', 1)
('without looking up', 1)
('looking up from', 1)
('up from what', 1)
('from what they', 1)
('were writing and', 1)
('writing and it', 1)
('only when the', 1)
('when the c

## 1.1.2. Analiza korpusa sa stemiranjem

U ovom dijelu napravila sam analizu unigrama, bigrama i trigrama korpusa sa stemiranjem. Također kao i u prethodnom poglavlju, prvo sam svorila listu rečenica koje se sastoje od n-grama, zatim sam stvorila rječnik kojem su ključevi n-grami, a vrijednosti broj pojavljivanja u korpusu i nakon toga sam sortirala rječnik u padajućem poretku.

Kako je Porterov algoritam najčešći alat za stemiranje (izvlačenje korijena riječi) u engleskom jeziku, a moj korpus je na engleskom, tako sam odlučila koristiti upravo njega. Upotrijebila sam gotovu funkciju PorterStemmer.

In [407]:
from nltk.stem import PorterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize

ps = PorterStemmer()

### Unigrami

Broj unigrama u korpusu je 22007 (broj riječi), naravno kao i maloprije u korpusu bez stemiranja, a broj različitih unigrama je 2092.

In [408]:
recenice_stemiranih_unigrama=[]
recenica=[]
for i in recenice_unigrama:
    for j in i:
        recenica.append(ps.stem(j))
    recenice_stemiranih_unigrama.append(recenica)
    recenica=[]
br=0
for i in recenice_stemiranih_unigrama:
    for j in i:
        br=br+1
print(br)

22007


In [409]:
rjecnik_stemiranih_unigrama={}
for recenica in recenice_stemiranih_unigrama:
    for rijec in recenica:
        if rijec not in rjecnik_stemiranih_unigrama:
            rjecnik_stemiranih_unigrama[rijec]=1
        else:
            rjecnik_stemiranih_unigrama[rijec]+=1
print(len(rjecnik_stemiranih_unigrama))

2092


Unigram koji se najviše puta pojavljuje je 'the', ali sada 1147 puta. Primjetimo da je to veći broj od broja pojavljivanja u korpusu bez stemiranja. Razlog je što su ovdje u tih 1147 uključeni i 'the' i 'The'.

In [410]:
for unigram in sorted(rjecnik_stemiranih_unigrama.items(), key=lambda item: item[1], reverse=True):
    print(unigram)

('the', 1147)
('to', 753)
('and', 642)
('hi', 550)
('he', 494)
('of', 429)
('wa', 409)
('had', 352)
('in', 338)
('it', 334)
('that', 333)
('a', 283)
('as', 232)
('gregor', 199)
('with', 199)
('she', 196)
('him', 188)
('her', 187)
('would', 187)
('not', 176)
('but', 171)
('for', 166)
('at', 158)
('they', 156)
('on', 147)
('be', 145)
('all', 134)
('room', 133)
('from', 119)
('could', 119)
('have', 115)
('out', 114)
('there', 102)
('even', 102)
('been', 101)
("gregor'", 99)
('door', 97)
('father', 96)
('sister', 96)
('thi', 92)
('now', 89)
('himself', 87)
('if', 87)
('then', 84)
('back', 83)
('so', 83)
('mother', 83)
('He', 82)
('up', 81)
('into', 78)
('time', 74)
('did', 73)
('more', 71)
('their', 70)
('when', 68)
('were', 67)
('what', 66)
('about', 65)
('them', 64)
('way', 63)
('look', 61)
('onli', 61)
('one', 58)
('I', 57)
('do', 57)
('no', 56)
('than', 55)
('open', 55)
('by', 53)
('get', 52)
('other', 52)
('just', 51)
('said', 51)
('you', 50)
('littl', 49)
('go', 49)
('ani', 47)
('sti

('limpli', 1)
('instrument', 1)
('labori', 1)
('pressur', 1)
('pillow', 1)
('slip', 1)
('obsess', 1)
('owe', 1)
('thunder', 1)
('therebi', 1)
('halt', 1)
('repugn', 1)
('prevail', 1)
('proceed', 1)
('stagger', 1)
('nap', 1)
('introduct', 1)
('monster', 1)
('humanli', 1)
('dulli', 1)
('derang', 1)
('forehead', 1)
('plate', 1)
('occasion', 1)
("it'll", 1)
('tortur', 1)
('mechan', 1)
('My', 1)
('sympathi', 1)
('shrug', 1)
('displac', 1)
('persecut', 1)
('beyond', 1)
('comprehens', 1)
('protect', 1)
('pain-wrack', 1)
('requir', 1)
('deal', 1)
('repeatedli', 1)
('unhappi', 1)
("they'll", 1)
('pant', 1)
('separ', 1)
('distract', 1)
('sprung', 1)
('discoveri', 1)
('spindli', 1)
('unnatur', 1)
('ach', 1)
('altogeth', 1)
('decay', 1)
('inflam', 1)
('area', 1)
('strongli', 1)
('rumin', 1)
('tower', 1)
('weakli', 1)
('nostril', 1)
("they'd", 1)
('brief', 1)
('special', 1)
('purpos', 1)
('martyr', 1)
('attribut', 1)
('tickl', 1)
('nuisanc', 1)
('resist', 1)
('whistl', 1)
('yank', 1)
("'ave", 1)
('

### Bigrami

Broj bigrama u korpusu je 21208, a broj različitih bigrama je 12175.

In [411]:
recenice_stemiranih_bigrama=[]
recenica=[]
for i in recenice_stemiranih_unigrama:
    for j in range(0,len(i)-1):
        recenica.append(i[j]+" "+i[j+1])
    recenice_stemiranih_bigrama.append(recenica)
    recenica=[]
br=0
for i in recenice_stemiranih_bigrama:
    for j in i:
        br=br+1
print(br)

21208


In [412]:
rjecnik_stemiranih_bigrama={}
for recenica in recenice_stemiranih_bigrama:
    for rijec in recenica:
        if rijec not in rjecnik_stemiranih_bigrama:
            rjecnik_stemiranih_bigrama[rijec]=1
        else:
            rjecnik_stemiranih_bigrama[rijec]+=1
print(len(rjecnik_stemiranih_bigrama))

12175


Bigram koji se najviše puta pojavljuje je 'of the' i to 96 puta kao i u korpusu bez stemiranja.

In [413]:
for bigram in sorted(rjecnik_stemiranih_bigrama.items(), key=lambda item: item[1], reverse=True):
    print(bigram)

('of the', 96)
('in the', 86)
('he had', 82)
('the door', 80)
('hi sister', 68)
('he wa', 67)
('it wa', 64)
('to the', 63)
('hi father', 60)
('had been', 54)
('he could', 53)
('on the', 53)
('that he', 52)
('as he', 45)
('of hi', 43)
('to be', 42)
('as if', 42)
('from the', 41)
('at the', 40)
('in hi', 39)
('hi mother', 38)
('the room', 38)
('and the', 36)
('want to', 36)
('the chief', 36)
('she had', 36)
('into the', 35)
('they had', 35)
('out of', 34)
('did not', 34)
('chief clerk', 34)
('all the', 33)
('he would', 33)
('with hi', 32)
('if he', 31)
('hi head', 31)
('hi room', 31)
('to him', 31)
('to get', 30)
('would have', 30)
('wa not', 30)
('with the', 29)
('and he', 29)
('the other', 29)
('a littl', 28)
('to do', 28)
('so that', 28)
('had to', 28)
('there wa', 27)
('to hi', 27)
('have to', 26)
('on hi', 24)
('with a', 24)
('when he', 24)
("gregor' father", 24)
('abl to', 23)
('It wa', 23)
('at all', 23)
('of it', 23)
('that wa', 22)
('gregor had', 22)
('could not', 22)
('had not'

('a panic', 2)
('far out', 2)
('the stairway', 2)
('to save', 2)
('save him', 2)
('question to', 2)
('away in', 2)
('hi posit', 2)
('put into', 2)
('parent did', 2)
('convinc that', 2)
('job would', 2)
('hi entir', 2)
('gregor though', 2)
('be held', 2)
('him she', 2)
('would close', 2)
('and talk', 2)
('him out', 2)
('hi shock', 2)
('not there', 2)
('do the', 2)
('the job', 2)
('still wa', 2)
('might not', 2)
('the banist', 2)
('over and', 2)
('to hold', 2)
('land on', 2)
('first time', 2)
('time that', 2)
('that day', 2)
('leg had', 2)
('he told', 2)
('him where', 2)
('wa soon', 2)
('would soon', 2)
('soon be', 2)
('at an', 2)
('an end', 2)
('the urg', 2)
('from side', 2)
('to side', 2)
('herself but', 2)
('arm outstretch', 2)
('and her', 2)
('her finger', 2)
('way she', 2)
('see gregor', 2)
('hurri backward', 2)
('had forgotten', 2)
('it when', 2)
('down on', 2)
('it without', 2)
('of coffe', 2)
('not help', 2)
('help himself', 2)
('the air', 2)
('the arm', 2)
('toward her', 2)
('th

('each individu', 1)
('individu word', 1)
('father went', 1)
('breakfast but', 1)
('whisper gregor', 1)
('door I', 1)
('I beg', 1)
('beg of', 1)
('gregor howev', 1)
('howev had', 1)
('no thought', 1)
('of open', 1)
('and instead', 1)
('instead congratul', 1)
('congratul himself', 1)
('himself for', 1)
('hi cautiou', 1)
('cautiou habit', 1)
('habit acquir', 1)
('acquir from', 1)
('hi travel', 1)
('travel of', 1)
('of lock', 1)
('lock all', 1)
('all door', 1)
('door at', 1)
('night even', 1)
('even when', 1)
('wa at', 1)
('peac without', 1)
('without be', 1)
('disturb to', 1)
('dress and', 1)
('have hi', 1)
('he consid', 1)
('consid what', 1)
('do next', 1)
('next as', 1)
('wa well', 1)
('bring hi', 1)
('thought to', 1)
('to ani', 1)
('ani sensibl', 1)
('sensibl conclus', 1)
('conclus by', 1)
('He rememb', 1)
('rememb that', 1)
('had often', 1)
('often felt', 1)
('slight pain', 1)
('bed perhap', 1)
('perhap caus', 1)
('lie awkwardli', 1)
('awkwardli but', 1)
('alway turn', 1)
('be pure',

('wide open', 1)
('open befor', 1)
('to slowli', 1)
('himself around', 1)
('around one', 1)
('it veri', 1)
('care if', 1)
('to fall', 1)
('fall flat', 1)
('befor enter', 1)
('still occupi', 1)
('thi difficult', 1)
('difficult movement', 1)
('movement unabl', 1)
('to anyth', 1)
('anyth els', 1)
('els when', 1)
('clerk exclaim', 1)
('exclaim a', 1)
('loud Oh', 1)
('which sound', 1)
('sound like', 1)
('the sough', 1)
('sough of', 1)
('the wind', 1)
('he also', 1)
('also saw', 1)
('saw him', 1)
('the nearest', 1)
('nearest to', 1)
('hand press', 1)
('hi open', 1)
('open mouth', 1)
('and slowli', 1)
('slowli retreat', 1)
('retreat as', 1)
('if driven', 1)
('driven by', 1)
('a steadi', 1)
('steadi and', 1)
('and invis', 1)
('invis forc', 1)
('mother her', 1)
('her hair', 1)
('hair still', 1)
('still dishevel', 1)
('dishevel from', 1)
('from bed', 1)
('bed despit', 1)
("clerk' be", 1)
('there look', 1)
('she unfold', 1)
('unfold her', 1)
('arm took', 1)
('took two', 1)
('two step', 1)
('step 

('he watch', 1)
('watch with', 1)
('with bulg', 1)
('bulg eye', 1)
('eye as', 1)
('sister unselfconsci', 1)
('unselfconsci took', 1)
('took a', 1)
('a broom', 1)
('broom and', 1)
('and swept', 1)
('swept up', 1)
('the left-ov', 1)
('left-ov mix', 1)
('mix them', 1)
('even touch', 1)
('touch at', 1)
('all as', 1)
('be use', 1)
('use ani', 1)
('she quickli', 1)
('quickli drop', 1)
('drop it', 1)
('all into', 1)
('a bin', 1)
('bin close', 1)
('it wooden', 1)
('wooden lid', 1)
('lid and', 1)
('carri everyth', 1)
('had hardli', 1)
('hardli turn', 1)
('turn her', 1)
('her back', 1)
('befor gregor', 1)
('wa how', 1)
('how gregor', 1)
('gregor receiv', 1)
('receiv hi', 1)
('food each', 1)
('each day', 1)
('day now', 1)
('now onc', 1)
('onc in', 1)
('maid were', 1)
('were still', 1)
('still asleep', 1)
('the second', 1)
('second time', 1)
('time after', 1)
('after everyon', 1)
('eaten their', 1)
('midday as', 1)
('parent would', 1)
('while then', 1)
('then as', 1)
('would send', 1)
('maid away'

('we take', 1)
('take now', 1)
('said grete', 1)
('look around', 1)
('eye met', 1)
('met those', 1)
('those of', 1)
('perhap onli', 1)
('onli becaus', 1)
('becaus her', 1)
('there she', 1)
('she remain', 1)
('calm bent', 1)
('bent her', 1)
('her so', 1)
('not look', 1)
('and said', 1)
('said albeit', 1)
('albeit hurriedli', 1)
('hurriedli and', 1)
('a tremor', 1)
('tremor in', 1)
('voic come', 1)
("on let'", 1)
("let' go", 1)
('what grete', 1)
('mind she', 1)
('take her', 1)
('mother somewher', 1)
('somewher safe', 1)
('safe and', 1)
('then chase', 1)
('him down', 1)
('down from', 1)
('well she', 1)
('could certainli', 1)
('certainli tri', 1)
('sat unyield', 1)
('unyield on', 1)
('rather jump', 1)
('jump at', 1)
("at grete'", 1)
("grete' face", 1)
("but grete'", 1)
("grete' word", 1)
('word had', 1)
('mother quit', 1)
('quit worri', 1)
('worri she', 1)
('she step', 1)
('step to', 1)
('side saw', 1)
('enorm brown', 1)
('brown patch', 1)
('patch against', 1)
('the flower', 1)
('flower of

('up hi', 1)
('room everi', 1)
('day instead', 1)
('of let', 1)
('her disturb', 1)
('him for', 1)
('reason whenev', 1)
('she felt', 1)
('felt like', 1)
('day earli', 1)
('while a', 1)
('heavi rain', 1)
('rain struck', 1)
('struck the', 1)
('the windowpan', 1)
('windowpan perhap', 1)
('perhap indic', 1)
('indic that', 1)
('that spring', 1)
('spring wa', 1)
('wa come', 1)
('come she', 1)
('she began', 1)
('way onc', 1)
('onc again', 1)
('so resent', 1)
('resent of', 1)
('it that', 1)
('her he', 1)
('wa slow', 1)
('and infirm', 1)
('infirm but', 1)
('wa like', 1)
('of attack', 1)
('of be', 1)
('be afraid', 1)
('afraid the', 1)
('charwoman just', 1)
('just lift', 1)
('chair from', 1)
('from near', 1)
('near the', 1)
('there with', 1)
('mouth open', 1)
('open clearli', 1)
('clearli intend', 1)
('intend not', 1)
('to close', 1)
('close her', 1)
('mouth until', 1)
('until the', 1)
('chair in', 1)
('hand had', 1)
('been slam', 1)
('slam down', 1)
('you come', 1)
('come ani', 1)
('ani closer', 

('wife on', 1)
('one arm', 1)
('daughter on', 1)
('been cri', 1)
('cri a', 1)
('littl grete', 1)
('grete now', 1)
('then press', 1)
('face against', 1)
('against her', 1)
("her father'", 1)
("father' arm", 1)
('leav my', 1)
('my home', 1)
('samsa indic', 1)
('indic the', 1)
('without let', 1)
('women from', 1)
('from him', 1)
('what do', 1)
('do you', 1)
('you mean', 1)
('gentlemen somewhat', 1)
('somewhat disconcert', 1)
('disconcert and', 1)
('he smile', 1)
('smile sweetli', 1)
('two held', 1)
('held their', 1)
('behind their', 1)
('their back', 1)
('continu rub', 1)
('rub them', 1)
('them togeth', 1)
('togeth in', 1)
('in gleeful', 1)
('gleeful anticip', 1)
('anticip of', 1)
('loud quarrel', 1)
('quarrel which', 1)
('which could', 1)
('onli end', 1)
('end in', 1)
('their favour', 1)
('I mean', 1)
('mean just', 1)
('said answer', 1)
('answer mr.', 1)
('two companion', 1)
('companion went', 1)
('line toward', 1)
('there still', 1)
('still look', 1)
('ground as', 1)
('the content', 1)


### Trigrami

Broj trigrama u korpusu je 20420, a broj različitih trigrama je 18203.

In [414]:
recenice_stemiranih_trigrama=[]
recenica=[]
for i in recenice_stemiranih_unigrama:
    for j in range(0,len(i)-2):
        recenica.append(i[j]+" "+i[j+1]+" "+i[j+2])
    recenice_stemiranih_trigrama.append(recenica)
    recenica=[]
br=0
for i in recenice_stemiranih_trigrama:
    for j in i:
        br=br+1
print(br)

20420


In [415]:
rjecnik_stemiranih_trigrama={}
for recenica in recenice_stemiranih_trigrama:
    for rijec in recenica:
        if rijec not in rjecnik_stemiranih_trigrama:
            rjecnik_stemiranih_trigrama[rijec]=1
        else:
            rjecnik_stemiranih_trigrama[rijec]+=1
print(len(rjecnik_stemiranih_trigrama))

18203


Trigram koji se najviše puta pojavljuje je 'the chief clerk' i to 33 puta.

In [416]:
for trigram in sorted(rjecnik_stemiranih_trigrama.items(), key=lambda item: item[1], reverse=True):
    print(trigram)

('the chief clerk', 33)
('open the door', 15)
('the live room', 15)
('the three gentlemen', 14)
('out of the', 13)
('he had been', 13)
('the door and', 12)
('that he had', 10)
('that he could', 10)
('one of the', 10)
('of hi bodi', 10)
('as if he', 10)
('in front of', 10)
('so that he', 9)
('chest of drawer', 9)
('he would have', 9)
('would have been', 9)
('he had to', 9)
('that he wa', 9)
('on the floor', 9)
('under the couch', 9)
('mother and sister', 9)
('would have to', 8)
('he did not', 8)
('he want to', 8)
('for him to', 8)
('to the door', 8)
('in the even', 8)
('the next room', 8)
('the door to', 8)
('into hi room', 8)
('that they had', 8)
('on hi back', 7)
('that it wa', 7)
('the chest of', 7)
('of the bed', 7)
('there wa a', 7)
('the other side', 7)
('he could not', 7)
('the door of', 7)
('in the morn', 7)
('in hi room', 7)
('to open the', 7)
('on the other', 7)
('over to the', 7)
('and he wa', 7)
('of the door', 7)
('to hi father', 7)
('and it wa', 7)
('where he wa', 6)
('bac

('into hi former', 1)
('hi former posit', 1)
('get up earli', 1)
('up earli all', 1)
('earli all the', 1)
('time he thought', 1)
('thought it make', 1)
('it make you', 1)
('make you stupid', 1)
('to get enough', 1)
('get enough sleep', 1)
('other travel salesmen', 1)
('travel salesmen live', 1)
('salesmen live a', 1)
('live a life', 1)
('a life of', 1)
('life of luxuri', 1)
('for instanc whenev', 1)
('instanc whenev I', 1)
('whenev I go', 1)
('I go back', 1)
('to the guest', 1)
('the guest hous', 1)
('guest hous dure', 1)
('hous dure the', 1)
('dure the morn', 1)
('the morn to', 1)
('morn to copi', 1)
('to copi out', 1)
('copi out the', 1)
('out the contract', 1)
('the contract these', 1)
('contract these gentlemen', 1)
('these gentlemen are', 1)
('gentlemen are alway', 1)
('are alway still', 1)
('alway still sit', 1)
('still sit there', 1)
('sit there eat', 1)
('there eat their', 1)
('eat their breakfast', 1)
('I ought to', 1)
('ought to just', 1)
('to just tri', 1)
('just tri that', 

('first word of', 1)
('word of greet', 1)
('of greet and', 1)
('greet and he', 1)
('and he knew', 1)
('he knew who', 1)
('knew who it', 1)
('wa the chief', 1)
('whi did gregor', 1)
('did gregor have', 1)
('gregor have to', 1)
('to be the', 1)
('onli one condemn', 1)
('one condemn to', 1)
('condemn to work', 1)
('to work for', 1)
('work for a', 1)
('for a compani', 1)
('a compani where', 1)
('compani where they', 1)
('where they immedi', 1)
('they immedi becam', 1)
('immedi becam highli', 1)
('becam highli suspici', 1)
('highli suspici at', 1)
('suspici at the', 1)
('the slightest shortcom', 1)
('were all employe', 1)
('all employe everi', 1)
('employe everi one', 1)
('everi one of', 1)
('of them lout', 1)
('them lout wa', 1)
('lout wa there', 1)
('wa there not', 1)
('there not one', 1)
('not one of', 1)
('of them who', 1)
('them who wa', 1)
('who wa faith', 1)
('wa faith and', 1)
('faith and devot', 1)
('and devot who', 1)
('devot who would', 1)
('who would go', 1)
('would go so', 1)
(

('differ from the', 1)
('from the way', 1)
('the way that', 1)
('way that a', 1)
('that a human', 1)
('a human cough', 1)
('human cough and', 1)
('cough and he', 1)
('no longer sure', 1)
('longer sure he', 1)
('sure he could', 1)
('he could judg', 1)
('could judg thi', 1)
('judg thi for', 1)
('thi for himself', 1)
('meanwhil it had', 1)
('it had becom', 1)
('had becom veri', 1)
('becom veri quiet', 1)
('veri quiet in', 1)
('quiet in the', 1)
('perhap hi parent', 1)
('hi parent were', 1)
('parent were sat', 1)
('were sat at', 1)
('the tabl whisper', 1)
('tabl whisper with', 1)
('whisper with the', 1)
('chief clerk or', 1)
('clerk or perhap', 1)
('or perhap they', 1)
('perhap they were', 1)
('were all press', 1)
('all press against', 1)
('press against the', 1)
('gregor slowli push', 1)
('slowli push hi', 1)
('push hi way', 1)
('door with the', 1)
('with the chair', 1)
('onc there he', 1)
('there he let', 1)
('go of it', 1)
('it and threw', 1)
('and threw himself', 1)
('onto the door', 1

('run after the', 1)
('after the chief', 1)
('clerk himself or', 1)
('himself or at', 1)
('least not imped', 1)
('not imped gregor', 1)
('imped gregor as', 1)
('as he ran', 1)
('he ran after', 1)
('ran after him', 1)
("after him gregor'", 1)
("him gregor' father", 1)
("gregor' father seiz", 1)
('father seiz the', 1)
('seiz the chief', 1)
("chief clerk' stick", 1)
("clerk' stick in", 1)
('in hi right', 1)
('right hand (the', 1)
('hand (the chief', 1)
('(the chief clerk', 1)
('clerk had left', 1)
('had left it', 1)
('left it behind', 1)
('it behind on', 1)
('behind on a', 1)
('on a chair', 1)
('a chair along', 1)
('chair along with', 1)
('with hi hat', 1)
('hi hat and', 1)
('hat and overcoat)', 1)
('and overcoat) pick', 1)
('overcoat) pick up', 1)
('pick up a', 1)
('up a larg', 1)
('a larg newspap', 1)
('larg newspap from', 1)
('newspap from the', 1)
('tabl with hi', 1)
('with hi left', 1)
('hi left and', 1)
('left and use', 1)
('and use them', 1)
('use them to', 1)
('them to drive', 1)


('greedili at the', 1)
('at the chees', 1)
('the chees which', 1)
('chees which had', 1)
('which had immedi', 1)
('had immedi almost', 1)
('immedi almost compellingli', 1)
('almost compellingli attract', 1)
('compellingli attract him', 1)
('attract him much', 1)
('him much more', 1)
('much more than', 1)
('than the other', 1)
('the other food', 1)
('other food on', 1)
('on the newspap', 1)
('quickli one after', 1)
('after anoth hi', 1)
('anoth hi eye', 1)
('hi eye water', 1)
('eye water with', 1)
('water with pleasur', 1)
('with pleasur he', 1)
('pleasur he consum', 1)
('he consum the', 1)
('consum the chees', 1)
('the chees the', 1)
('chees the veget', 1)
('the veget and', 1)
('veget and the', 1)
('and the sauc', 1)
('the sauc the', 1)
('sauc the fresh', 1)
('the fresh food', 1)
('fresh food on', 1)
('other hand he', 1)
("hand he didn't", 1)
("he didn't like", 1)
("didn't like at", 1)
('like at all', 1)
('all and even', 1)
('and even drag', 1)
('even drag the', 1)
('drag the thing', 1

('and found him', 1)
('found him still', 1)
('him still stare', 1)
('still stare out', 1)
('stare out the', 1)
('the window motionless', 1)
('window motionless and', 1)
('motionless and just', 1)
('and just where', 1)
('just where he', 1)
('where he would', 1)
('he would be', 1)
('would be most', 1)
('be most horribl', 1)
('In itself hi', 1)
("itself hi sister'", 1)
("hi sister' not", 1)
("sister' not come", 1)
('not come into', 1)
('room would have', 1)
('have been no', 1)
('been no surpris', 1)
('no surpris for', 1)
('surpris for gregor', 1)
('for gregor as', 1)
('gregor as it', 1)
('as it would', 1)
('have been difficult', 1)
('been difficult for', 1)
('difficult for her', 1)
('her to immedi', 1)
('to immedi open', 1)
('immedi open the', 1)
('window while he', 1)
('while he wa', 1)
('he wa still', 1)
('still there but', 1)
('there but not', 1)
('but not onli', 1)
('onli did she', 1)
('did she not', 1)
('she not come', 1)
('not come in', 1)
('come in she', 1)
('in she went', 1)
('she

('other room catch', 1)
('room catch their', 1)
('catch their breath', 1)
('their breath he', 1)
('breath he salli', 1)
('he salli out', 1)
('salli out chang', 1)
('out chang direct', 1)
('chang direct four', 1)
('direct four time', 1)
('four time not', 1)
('time not know', 1)
('not know what', 1)
('what he should', 1)
('he should save', 1)
('should save first', 1)
('save first befor', 1)
('first befor hi', 1)
('befor hi attent', 1)
('hi attent wa', 1)
('attent wa suddenli', 1)
('wa suddenli caught', 1)
('suddenli caught by', 1)
('caught by the', 1)
('by the pictur', 1)
('the pictur on', 1)
('pictur on the', 1)
('the wall which', 1)
('wall which wa', 1)
('which wa alreadi', 1)
('wa alreadi denud', 1)
('alreadi denud of', 1)
('denud of everyth', 1)
('of everyth els', 1)
('everyth els that', 1)
('els that had', 1)
('had been on', 1)
('been on it', 1)
('on it of', 1)
('it of the', 1)
('of the ladi', 1)
('the ladi dress', 1)
('ladi dress in', 1)
('dress in copiou', 1)
('in copiou fur', 1)


('sister to look', 1)
('gregor would often', 1)
('would often spend', 1)
('often spend the', 1)
('spend the whole', 1)
('the whole even', 1)
('whole even look', 1)
('even look at', 1)
('all the stain', 1)
('the stain on', 1)
('stain on thi', 1)
('on thi coat', 1)
('thi coat with', 1)
('coat with it', 1)
('it gold button', 1)
('gold button alway', 1)
('button alway kept', 1)
('alway kept polish', 1)
('kept polish and', 1)
('polish and shini', 1)
('and shini while', 1)
('shini while the', 1)
('while the old', 1)
('the old man', 1)
('old man in', 1)
('man in it', 1)
('in it would', 1)
('it would sleep', 1)
('would sleep highli', 1)
('sleep highli uncomfort', 1)
('highli uncomfort but', 1)
('uncomfort but peac', 1)
('soon as it', 1)
('as it struck', 1)
('it struck ten', 1)
("struck ten gregor'", 1)
("ten gregor' mother", 1)
('mother would speak', 1)
('would speak gentli', 1)
('speak gentli to', 1)
('gentli to hi', 1)
('father to wake', 1)
('to wake him', 1)
('wake him and', 1)
('him and tr

('to the kitchen', 1)
('It wa to', 1)
('wa to hi', 1)
('to hi satisfact', 1)
('hi satisfact and', 1)
("satisfact and gregor'", 1)
("and gregor' mother", 1)
('and sister who', 1)
('had been look', 1)
('been look on', 1)
('look on anxious', 1)
('on anxious began', 1)
('anxious began to', 1)
('began to breath', 1)
('to breath again', 1)
('breath again and', 1)
('again and smile', 1)
('the famili themselv', 1)
('famili themselv ate', 1)
('themselv ate in', 1)
('ate in the', 1)
("nonetheless gregor' father", 1)
("gregor' father came", 1)
('father came into', 1)
('live room befor', 1)
('room befor he', 1)
('befor he went', 1)
('he went into', 1)
('went into the', 1)
('the kitchen bow', 1)
('kitchen bow onc', 1)
('bow onc with', 1)
('onc with hi', 1)
('with hi cap', 1)
('hi cap in', 1)
('cap in hi', 1)
('hand and did', 1)
('and did hi', 1)
('did hi round', 1)
('hi round of', 1)
('round of the', 1)
('of the tabl', 1)
('the gentlemen stood', 1)
('gentlemen stood as', 1)
('stood as one', 1)
('as

('As it is', 1)
('it is thi', 1)
('is thi anim', 1)
('thi anim is', 1)
('anim is persecut', 1)
('is persecut us', 1)
("persecut us it'", 1)
("us it' driven", 1)
("it' driven out", 1)
('driven out our', 1)
('out our tenant', 1)
('our tenant it', 1)
('tenant it obvious', 1)
('it obvious want', 1)
('obvious want to', 1)
('to take over', 1)
('over the whole', 1)
('the whole flat', 1)
('whole flat and', 1)
('flat and forc', 1)
('and forc us', 1)
('forc us to', 1)
('us to sleep', 1)
('sleep on the', 1)
('on the street', 1)
('father look just', 1)
('look just look', 1)
('just look she', 1)
('look she suddenli', 1)
('she suddenli scream', 1)
("suddenli scream he'", 1)
("scream he' start", 1)
("he' start again", 1)
('In her alarm', 1)
('her alarm which', 1)
('alarm which wa', 1)
('which wa total', 1)
('wa total beyond', 1)
("total beyond gregor'", 1)
("beyond gregor' comprehens", 1)
("gregor' comprehens hi", 1)
('comprehens hi sister', 1)
('hi sister even', 1)
('sister even abandon', 1)
('even 

('of irrit to', 1)
('irrit to mr.', 1)
('to mr. samsa', 1)
('mr. samsa all', 1)
('samsa all the', 1)
('the time she', 1)
('time she had', 1)
('had been work', 1)
('been work for', 1)
('work for them', 1)
('for them sway', 1)
('them sway gentli', 1)
('sway gentli in', 1)
('gentli in all', 1)
('in all direct', 1)
('what is it', 1)
('is it you', 1)
('it you want', 1)
('you want then', 1)
('mrs. samsa whom', 1)
('samsa whom the', 1)
('whom the cleaner', 1)
('the cleaner had', 1)
('cleaner had the', 1)
('had the most', 1)
('the most respect', 1)
('most respect for', 1)
('ye she answer', 1)
('she answer and', 1)
('answer and broke', 1)
('and broke into', 1)
('broke into a', 1)
('into a friendli', 1)
('a friendli laugh', 1)
('friendli laugh that', 1)
('laugh that made', 1)
('made her unabl', 1)
('her unabl to', 1)
('unabl to speak', 1)
('to speak straight', 1)
('speak straight away', 1)
('straight away well', 1)
('away well then', 1)
('well then that', 1)
('then that thing', 1)
('that thing i

## 1.2. Analiza korpusa za treniranje

## 1.2.1. Analiza korpusa za treniranje bez stemiranja

U ovom dijelu napravila sam analizu unigrama, bigrama i trigrama korpusa za treniranje bez stemiranja. Prvo sam stvorila listu rečenica koje se sastoje od n-grama, zatim sam stvorila rječnik kojem su ključevi n-grami, a vrijednosti broj pojavljivanja u korpusu i nakon toga sam sortirala rječnik u padajućem poretku.

### Unigrami

Broj unigrama u korpusu je 16585, a broj različitih unigrama je 2367.
Unigram koji se najviše puta pojavljuje je 'the' i to 831 puta.

In [493]:
recenice_unigrama_treniranje=[]
recenica=''
for i in range(0,len(korpus_za_treniranje)):
    if (korpus_za_treniranje[i]=='.' and korpus_za_treniranje[i-2:i]!="Mr" and korpus_za_treniranje[i-3:i]!="Mrs") or korpus_za_treniranje[i]=='!' or korpus_za_treniranje[i]=='?':
        recenice_unigrama_treniranje.append(recenica.split())
        recenica=''
    else:
        recenica=recenica+korpus_za_treniranje[i]
br=0
for i in recenice_unigrama_treniranje:
    for j in i:
        br=br+1
print(br)

rjecnik_unigrama_treniranje={}
for recenica in recenice_unigrama_treniranje:
    for rijec in recenica:
        if rijec not in rjecnik_unigrama_treniranje:
            rjecnik_unigrama_treniranje[rijec]=1
        else:
            rjecnik_unigrama_treniranje[rijec]+=1
print(len(rjecnik_unigrama_treniranje))

for unigram in sorted(rjecnik_unigrama_treniranje.items(), key=lambda item: item[1], reverse=True):
    print(unigram)

16585
2367
('the', 831)
('to', 583)
('and', 432)
('he', 417)
('his', 416)
('of', 338)
('was', 315)
('had', 255)
('that', 251)
('in', 240)
('it', 234)
('a', 225)
('as', 178)
('Gregor', 165)
('would', 165)
('him', 152)
('not', 137)
('with', 128)
('she', 124)
('for', 121)
('at', 117)
('her', 108)
('on', 107)
('but', 107)
('be', 99)
('could', 95)
('all', 93)
('have', 92)
('room', 91)
('from', 88)
('out', 81)
('himself', 78)
('there', 77)
('been', 76)
('sister', 72)
('even', 71)
('they', 71)
('door', 70)
('father', 70)
("Gregor's", 69)
('so', 66)
('if', 64)
('mother', 64)
('back', 60)
('now', 60)
('up', 59)
('He', 58)
('this', 58)
('about', 55)
('did', 55)
('more', 54)
('into', 52)
('then', 49)
('when', 48)
('than', 48)
('were', 48)
('time', 47)
('way', 45)
('by', 44)
('what', 44)
('no', 44)
('only', 43)
('I', 42)
('any', 39)
('them', 39)
('you', 38)
('one', 38)
('little', 37)
('get', 37)
('chief', 37)
('do', 36)
('see', 35)
('much', 34)
('or', 34)
('clerk', 34)
('go', 33)
('still', 33)
('j

('droplets', 1)
('number', 1)
('photograph', 1)
('lieutenant', 1)
('army', 1)
('sword', 1)
('carefree', 1)
('respect', 1)
('bearing', 1)
('pack', 1)
('commercial', 1)
('traveller', 1)
('arduous', 1)
('accurately', 1)
('temporarily', 1)
('remember', 1)
('achieved', 1)
('diligence', 1)
("You're", 1)
('our', 1)
('trapped', 1)
('likes', 1)
('wage', 1)
('soft', 1)
('prejudice', 1)
('staff', 1)
('businessman', 1)
('mistakes', 1)
('harshly', 1)
('victim', 1)
('gossip', 1)
('groundless', 1)
('complaints', 1)
('defend', 1)
('arrive', 1)
('trip', 1)
('harmful', 1)
('effects', 1)
('protruding', 1)
('lips', 1)
('stared', 1)
('trembling', 1)
('shoulders', 1)
('steadily', 1)
('gradually', 1)
('prohibition', 1)
('sudden', 1)
('supernatural', 1)
('waiting', 1)
('extreme', 1)
('besides', 1)
('won', 1)
('depended', 1)
('clever', 1)
('lover', 1)
('considering', 1)
('speech', 1)
('reach', 1)
('ridiculously', 1)
('scream', 1)
('sought', 1)
('landed', 1)
('numerous', 1)
('solid', 1)
('believing', 1)
('sorro

### Bigrami

Broj bigrama u korpusu je 16008, a broj različitih bigrama je 10070. Bigram koji se najviše puta pojavljuje je ' of the' i to 78 puta.

In [494]:
recenice_bigrama_treniranje=[]
recenica=[]
for i in recenice_unigrama_treniranje:
    for j in range(0,len(i)-1):
        recenica.append(i[j]+" "+i[j+1])
    recenice_bigrama_treniranje.append(recenica)
    recenica=[]
br=0
for i in recenice_bigrama_treniranje:
    for j in i:
        br=br+1
print(br)

    
rjecnik_bigrama_treniranje={}
for recenica in recenice_bigrama_treniranje:
    for rijec in recenica:
        if rijec not in rjecnik_bigrama_treniranje:
            rjecnik_bigrama_treniranje[rijec]=1
        else:
            rjecnik_bigrama_treniranje[rijec]+=1
print(len(rjecnik_bigrama_treniranje))

for bigram in sorted(rjecnik_bigrama_treniranje.items(), key=lambda item: item[1], reverse=True):
    print(bigram)

16008
10070
('of the', 78)
('he had', 68)
('in the', 58)
('the door', 57)
('he was', 51)
('it was', 49)
('his father', 49)
('his sister', 49)
('to the', 48)
('he could', 46)
('on the', 46)
('that he', 42)
('as he', 36)
('of his', 35)
('to be', 35)
('had been', 34)
('the chief', 34)
('chief clerk', 34)
('in his', 32)
('from the', 32)
('the room', 29)
('he would', 28)
('his mother', 28)
('if he', 27)
('would have', 27)
('did not', 27)
('had to', 27)
('out of', 26)
('at the', 26)
('to do', 26)
('so that', 25)
('all the', 25)
('to get', 25)
('and the', 25)
('into the', 25)
('as if', 25)
('she had', 23)
('his head', 22)
('able to', 22)
('have to', 22)
('when he', 22)
('was not', 22)
('to him', 21)
('and he', 21)
('a little', 20)
('with the', 20)
('to his', 20)
('his room', 20)
('there was', 19)
('the other', 19)
('with his', 19)
('It was', 18)
('on his', 17)
('was a', 17)
('with a', 17)
('have been', 17)
('to see', 17)
('wanted to', 17)
('could not', 17)
('him to', 17)
('that she', 17)
('ha

('way even', 2)
('but even', 2)
('day the', 2)
('maid had', 2)
('without delay', 2)
('a quarter', 2)
('quarter of', 2)
('an hour', 2)
('no-one had', 2)
('although that', 2)
('very much', 2)
('heard how', 2)
('another to', 2)
('and fetch', 2)
('nothing she', 2)
('it but', 2)
('and no', 2)
('he stood', 2)
('his business', 2)
('when it', 2)
('Gregor heard', 2)
('that nothing', 2)
('family to', 2)
('total despair', 2)
('despair and', 2)
('to earn', 2)
('quite different', 2)
('astonished and', 2)
('times and', 2)
('to bear', 2)
('family they', 2)
('was glad', 2)
('very fond', 2)
('the conservatory', 2)
('conversation with', 2)
('became too', 2)
('too tired', 2)
('tired to', 2)
('pull it', 2)
('up again', 2)
('only then', 2)
('be taken', 2)
('several times', 2)
('partly because', 2)
('mother did', 2)
('understand everything', 2)
('old days', 2)
('up all', 2)
('pleasure at', 2)
('money to', 2)
('was certainly', 2)
('certainly not', 2)
('to live', 2)
('was enough', 2)
('one or', 2)
('or two', 

('final decision', 1)
('decision very', 1)
('very soon', 1)
('a ring', 1)
('ring at', 1)
("That'll be", 1)
('be someone', 1)
('someone from', 1)
('and froze', 1)
('froze very', 1)
('still although', 1)
('although his', 1)
('legs only', 1)
('only became', 1)
('became all', 1)
('more lively', 1)
('lively as', 1)
('they danced', 1)
('danced around', 1)
('For a', 1)
('moment everything', 1)
('everything remained', 1)
('remained quiet', 1)
("They're not", 1)
('not opening', 1)
('himself caught', 1)
('caught in', 1)
('some nonsensical', 1)
('nonsensical hope', 1)
('then of', 1)
("the maid's", 1)
("maid's firm", 1)
('firm steps', 1)
('steps went', 1)
('went to', 1)
('as ever', 1)
('ever and', 1)
('and opened', 1)
('opened it', 1)
("the visitor's", 1)
("visitor's first", 1)
('words of', 1)
('of greeting', 1)
('greeting and', 1)
('knew who', 1)
('Why did', 1)
('one condemned', 1)
('condemned to', 1)
('a company', 1)
('company where', 1)
('they immediately', 1)
('immediately became', 1)
('became

('any harder', 1)
('harder for', 1)
('me than', 1)
('they are', 1)
('are already', 1)
('already and', 1)
("and don't", 1)
("don't take", 1)
('take sides', 1)
('sides against', 1)
('against me', 1)
('me at', 1)
('that nobody', 1)
('nobody likes', 1)
('likes the', 1)
('the travellers', 1)
('They think', 1)
('think we', 1)
('we earn', 1)
('earn an', 1)
('enormous wage', 1)
('wage as', 1)
('a soft', 1)
('soft time', 1)
("That's just", 1)
('just prejudice', 1)
('prejudice but', 1)
('no particular', 1)
('think better', 1)
('you sir', 1)
('sir you', 1)
('have a', 1)
('the staff', 1)
('staff in', 1)
('fact if', 1)
('I can', 1)
('can say', 1)
('say this', 1)
('this in', 1)
('in confidence', 1)
('confidence a', 1)
('boss himself', 1)
("himself it's", 1)
("it's very", 1)
('very easy', 1)
('easy for', 1)
('a businessman', 1)
('businessman like', 1)
('like him', 1)
('make mistakes', 1)
('mistakes about', 1)
('his employees', 1)
('employees and', 1)
('and judge', 1)
('judge them', 1)
('them more', 1

('consumed the', 1)
('cheese the', 1)
('the vegetables', 1)
('vegetables and', 1)
('the sauce', 1)
('sauce the', 1)
('fresh foods', 1)
('hand he', 1)
("didn't like", 1)
('like at', 1)
('even dragged', 1)
('dragged the', 1)
('eat a', 1)
('little way', 1)
('way away', 1)
('from them', 1)
('them because', 1)
("couldn't stand", 1)
('stand the', 1)
('Long after', 1)
('had finished', 1)
('finished eating', 1)
('eating and', 1)
('and lay', 1)
('lay lethargic', 1)
('lethargic in', 1)
('same place', 1)
('sister slowly', 1)
('slowly turned', 1)
('sign to', 1)
('should withdraw', 1)
('was immediately', 1)
('immediately startled', 1)
('startled although', 1)
('been half', 1)
('half asleep', 1)
('hurried back', 1)
('back under', 1)
('he needed', 1)
('needed great', 1)
('great self-control', 1)
('self-control to', 1)
('stay there', 1)
('there even', 1)
('even for', 1)
('the short', 1)
('short time', 1)
('as eating', 1)
('eating so', 1)
('much food', 1)
('food had', 1)
('had rounded', 1)
('rounded ou

('needed a', 1)
('of room', 1)
('in whereas', 1)
('whereas the', 1)
('furniture as', 1)
('as anyone', 1)
('anyone could', 1)
('see was', 1)
('no use', 1)
('use to', 1)
('him at', 1)
('Girls of', 1)
('that age', 1)
('age though', 1)
('though do', 1)
('do become', 1)
('become enthusiastic', 1)
('enthusiastic about', 1)
('things and', 1)
('and feel', 1)
('feel they', 1)
('must get', 1)
('get their', 1)
('way whenever', 1)
('whenever they', 1)
('they can', 1)
('Perhaps this', 1)
('was what', 1)
('what tempted', 1)
('tempted Grete', 1)
('Grete to', 1)
("make Gregor's", 1)
("Gregor's situation", 1)
('situation seem', 1)
('seem even', 1)
('more shocking', 1)
('shocking than', 1)
('than it', 1)
('do even', 1)
('probably be', 1)
('one who', 1)
('would dare', 1)
('dare enter', 1)
('enter a', 1)
('a room', 1)
('room dominated', 1)
('dominated by', 1)
('Gregor crawling', 1)
('walls by', 1)
('So she', 1)
('she refused', 1)
('mother dissuade', 1)
('dissuade her', 1)
('mother already', 1)
('already l

('their tears', 1)
('tears would', 1)
('would mingle', 1)
('mingle or', 1)
('or they', 1)
('would simply', 1)
('simply sit', 1)
('sit there', 1)
('there staring', 1)
('staring dry-eyed', 1)
('dry-eyed at', 1)
('Gregor hardly', 1)
('hardly slept', 1)
('slept at', 1)
('all either', 1)
('either night', 1)
('night or', 1)
('or day', 1)
('Sometimes he', 1)
('of taking', 1)
('taking over', 1)
("the family's", 1)
("family's affairs", 1)
('affairs just', 1)
('just like', 1)
('like before', 1)
('next time', 1)
('time the', 1)
('opened he', 1)
('had long', 1)
('long forgotten', 1)
('forgotten about', 1)
('clerk but', 1)
('would appear', 1)
('appear again', 1)
('thoughts the', 1)
('the salesmen', 1)
('salesmen and', 1)
('the apprentices', 1)
('apprentices that', 1)
('that stupid', 1)
('stupid teaboy', 1)
('teaboy two', 1)
('three friends', 1)
('friends from', 1)
('from other', 1)
('other businesses', 1)
('businesses one', 1)
('the chambermaids', 1)
('chambermaids from', 1)
('a provincial', 1)
('p

### Trigrami

Broj trigrama u korpusu je 15439, a broj različitih trigrama je 14052. Trigram koji se najviše puta pojavljuje je 'the chief clerk' i to 31 puta.

In [495]:
recenice_trigrama_treniranje=[]
recenica=[]
for i in recenice_unigrama_treniranje:
    for j in range(0,len(i)-2):
        recenica.append(i[j]+" "+i[j+1]+" "+i[j+2])
    recenice_trigrama_treniranje.append(recenica)
    recenica=[]
br=0
for i in recenice_trigrama_treniranje:
    for j in i:
        br=br+1
print(br)

    
rjecnik_trigrama_treniranje={}
for recenica in recenice_trigrama_treniranje:
    for rijec in recenica:
        if rijec not in rjecnik_trigrama_treniranje:
            rjecnik_trigrama_treniranje[rijec]=1
        else:
            rjecnik_trigrama_treniranje[rijec]+=1
print(len(rjecnik_trigrama_treniranje))

for trigram in sorted(rjecnik_trigrama_treniranje.items(), key=lambda item: item[1], reverse=True):
    print(trigram)

15439
14052
('the chief clerk', 31)
('out of the', 12)
('of his body', 10)
('he had been', 10)
('that he had', 9)
('chest of drawers', 9)
('would have been', 9)
('he had to', 9)
('the living room', 9)
('under the couch', 9)
('would have to', 8)
('he did not', 8)
('open the door', 8)
('the door and', 8)
('on the floor', 8)
('so that he', 7)
('that he could', 7)
('that it was', 7)
('of the bed', 7)
('he could not', 7)
('for him to', 7)
('as if he', 7)
('to the door', 7)
('to open the', 7)
('that he was', 7)
('mother and sister', 7)
('where he was', 6)
('the chest of', 6)
('that he would', 6)
('he would have', 6)
('one of the', 6)
('the other side', 6)
('he wanted to', 6)
('said to himself', 6)
('had to be', 6)
('on the other', 6)
('and he was', 6)
('into his room', 6)
('in front of', 6)
('to his father', 6)
('his father would', 6)
('from under the', 6)
('and if he', 5)
('on the table', 5)
('on his back', 5)
('back into his', 5)
('have to go', 5)
('he had not', 5)
('he would not', 5)
('at

('of service Gregor', 1)
('service Gregor had', 1)
('had never once', 1)
('never once yet', 1)
('once yet been', 1)
('yet been ill', 1)
('His boss would', 1)
('boss would certainly', 1)
('would certainly come', 1)
('certainly come round', 1)
('come round with', 1)
('round with the', 1)
('with the doctor', 1)
('the doctor from', 1)
('doctor from the', 1)
('from the medical', 1)
('the medical insurance', 1)
('medical insurance company', 1)
('insurance company accuse', 1)
('company accuse his', 1)
('accuse his parents', 1)
('his parents of', 1)
('parents of having', 1)
('of having a', 1)
('having a lazy', 1)
('a lazy son', 1)
('lazy son and', 1)
('son and accept', 1)
('and accept the', 1)
("accept the doctor's", 1)
("the doctor's recommendation", 1)
("doctor's recommendation not", 1)
('recommendation not to', 1)
('not to make', 1)
('to make any', 1)
('make any claim', 1)
('any claim as', 1)
('claim as the', 1)
('as the doctor', 1)
('the doctor believed', 1)
('doctor believed that', 1)
('b

('leave on the', 1)
('on the early', 1)
('the early train', 1)
("We don't know", 1)
("don't know what", 1)
('what to say', 1)
('to say to', 1)
('say to him', 1)
('And anyway he', 1)
('anyway he wants', 1)
('he wants to', 1)
('wants to speak', 1)
('speak to you', 1)
('to you personally', 1)
('So please open', 1)
('please open up', 1)
('open up this', 1)
('up this door', 1)
("I'm sure he'll", 1)
("sure he'll be", 1)
("he'll be good", 1)
('be good enough', 1)
('good enough to', 1)
('enough to forgive', 1)
('to forgive the', 1)
('forgive the untidiness', 1)
('the untidiness of', 1)
('untidiness of your', 1)
('of your room', 1)
('Then the chief', 1)
('chief clerk called', 1)
('clerk called Good', 1)
('called Good morning', 1)
('Good morning Mr.', 1)
('morning Mr. Samsa', 1)
("isn't well said", 1)
('well said his', 1)
('said his mother', 1)
('mother to the', 1)
('chief clerk while', 1)
('clerk while his', 1)
('while his father', 1)
('his father continued', 1)
('father continued to', 1)
('con

('the locksmith after', 1)
('locksmith after all', 1)
('Then he lay', 1)
('he lay his', 1)
('lay his head', 1)
('his head on', 1)
('head on the', 1)
('on the handle', 1)
('the handle of', 1)
('handle of the', 1)
('door to open', 1)
('to open it', 1)
('open it completely', 1)
('Because he had', 1)
('had to open', 1)
('the door in', 1)
('door in this', 1)
('this way it', 1)
('it was already', 1)
('was already wide', 1)
('already wide open', 1)
('wide open before', 1)
('open before he', 1)
('before he could', 1)
('He had first', 1)
('had first to', 1)
('first to slowly', 1)
('to slowly turn', 1)
('slowly turn himself', 1)
('turn himself around', 1)
('himself around one', 1)
('around one of', 1)
('double doors and', 1)
('doors and he', 1)
('and he had', 1)
('do it very', 1)
('it very carefully', 1)
('very carefully if', 1)
('carefully if he', 1)
('want to fall', 1)
('to fall flat', 1)
('fall flat on', 1)
('flat on his', 1)
('his back before', 1)
('back before entering', 1)
('before enterin

('he had no', 1)
('no choice as', 1)
('choice as he', 1)
('as he saw', 1)
('he saw to', 1)
('saw to his', 1)
('to his disgust', 1)
('his disgust that', 1)
('disgust that he', 1)
('he was quite', 1)
('was quite incapable', 1)
('quite incapable of', 1)
('incapable of going', 1)
('of going backwards', 1)
('going backwards in', 1)
('backwards in a', 1)
('in a straight', 1)
('a straight line', 1)
('straight line so', 1)
('line so he', 1)
('so he began', 1)
('he began as', 1)
('began as quickly', 1)
('as possible and', 1)
('possible and with', 1)
('and with frequent', 1)
('with frequent anxious', 1)
('frequent anxious glances', 1)
('anxious glances at', 1)
('glances at his', 1)
('father to turn', 1)
('to turn himself', 1)
('turn himself round', 1)
('It went very', 1)
('went very slowly', 1)
('very slowly but', 1)
('slowly but perhaps', 1)
('but perhaps his', 1)
('perhaps his father', 1)
('his father was', 1)
('father was able', 1)
('see his good', 1)
('his good intentions', 1)
('good intenti

('stand to have', 1)
('to have any', 1)
('have any more', 1)
('any more experience', 1)
('more experience of', 1)
('experience of his', 1)
('of his feeding', 1)
('his feeding than', 1)
('feeding than being', 1)
('than being told', 1)
('being told about', 1)
('told about it', 1)
('it and perhaps', 1)
('and perhaps his', 1)
('perhaps his sister', 1)
('his sister wanted', 1)
('sister wanted to', 1)
('wanted to spare', 1)
('to spare them', 1)
('spare them what', 1)
('them what distress', 1)
('what distress she', 1)
('distress she could', 1)
('she could as', 1)
('could as they', 1)
('they were indeed', 1)
('were indeed suffering', 1)
('indeed suffering enough', 1)
('It was impossible', 1)
('impossible for Gregor', 1)
('Gregor to find', 1)
('find out what', 1)
('out what they', 1)
('what they had', 1)
('they had told', 1)
('had told the', 1)
('told the doctor', 1)
('the locksmith that', 1)
('locksmith that first', 1)
('that first morning', 1)
('first morning to', 1)
('morning to get', 1)
('t

('spare her even', 1)
('her even this', 1)
('even this sight', 1)
('this sight he', 1)
('sight he spent', 1)
('he spent four', 1)
('spent four hours', 1)
('four hours carrying', 1)
('hours carrying the', 1)
('carrying the bedsheet', 1)
('the bedsheet over', 1)
('bedsheet over to', 1)
('to the couch', 1)
('the couch on', 1)
('couch on his', 1)
('his back and', 1)
('back and arranged', 1)
('and arranged it', 1)
('arranged it so', 1)
('he was completely', 1)
('was completely covered', 1)
('completely covered and', 1)
('covered and his', 1)
('sister would not', 1)
('see him even', 1)
('even if she', 1)
('if she bent', 1)
('she bent down', 1)
('If she did', 1)
('did not think', 1)
('not think this', 1)
('think this sheet', 1)
('this sheet was', 1)
('sheet was necessary', 1)
('was necessary then', 1)
('necessary then all', 1)
('then all she', 1)
('all she had', 1)
('do was take', 1)
('was take it', 1)
('take it off', 1)
('it off again', 1)
('off again as', 1)
('again as it', 1)
('it was clea

('the picture on', 1)
('picture on the', 1)
('the wall which', 1)
('wall which was', 1)
('which was already', 1)
('was already denuded', 1)
('already denuded of', 1)
('denuded of everything', 1)
('of everything else', 1)
('everything else that', 1)
('else that had', 1)
('had been on', 1)
('been on it', 1)
('on it of', 1)
('it of the', 1)
('of the lady', 1)
('the lady dressed', 1)
('lady dressed in', 1)
('dressed in copious', 1)
('in copious fur', 1)
('He hurried up', 1)
('hurried up onto', 1)
('onto the picture', 1)
('the picture and', 1)
('picture and pressed', 1)
('himself against its', 1)
('against its glass', 1)
('its glass it', 1)
('glass it held', 1)
('it held him', 1)
('held him firmly', 1)
('him firmly and', 1)
('firmly and felt', 1)
('and felt good', 1)
('felt good on', 1)
('good on his', 1)
('on his hot', 1)
('his hot belly', 1)
('This picture at', 1)
('picture at least', 1)
('at least now', 1)
('least now totally', 1)
('now totally covered', 1)
('totally covered by', 1)
('co

('he had become', 1)
('had become more', 1)
('become more obstinate', 1)
('more obstinate and', 1)
('obstinate and would', 1)
('and would always', 1)
('would always insist', 1)
('always insist on', 1)
('insist on staying', 1)
('on staying longer', 1)
('staying longer at', 1)
('longer at the', 1)
('the table even', 1)
('table even though', 1)
('though he regularly', 1)
('he regularly fell', 1)
('regularly fell asleep', 1)
('fell asleep and', 1)
('asleep and it', 1)
('it was then', 1)
('was then harder', 1)
('then harder than', 1)
('harder than ever', 1)
('than ever to', 1)
('ever to persuade', 1)
('him to exchange', 1)
('to exchange the', 1)
('exchange the chair', 1)
('the chair for', 1)
('chair for his', 1)
('for his bed', 1)
('Then however much', 1)
('however much mother', 1)
('much mother and', 1)
('sister would importune', 1)
('would importune him', 1)
('importune him with', 1)
('him with little', 1)
('with little reproaches', 1)
('little reproaches and', 1)
('reproaches and warning

## 1.2.2. Analiza korpusa za treniranje sa stemiranjem

U ovom dijelu napravila sam analizu unigrama, bigrama i trigrama korpusa za treniranje sa stemiranjem. Prvo sam stvorila listu rečenica koje se sastoje od n-grama, zatim sam stvorila rječnik kojem su ključevi n-grami, a vrijednosti broj pojavljivanja u korpusu i nakon toga sam sortirala rječnik u padajućem poretku.

### Unigrami

Broj unigrama u korpusu je 16585, a broj različitih unigrama je 1833. Unigram koji se najviše puta pojavljuje je 'the' i to 859 puta.

In [496]:
recenice_stemiranih_unigrama_treniranje=[]
recenica=[]
for i in recenice_unigrama_treniranje:
    for j in i:
        recenica.append(ps.stem(j))
    recenice_stemiranih_unigrama_treniranje.append(recenica)
    recenica=[]
br=0
for i in recenice_stemiranih_unigrama_treniranje:
    for j in i:
        br=br+1
print(br)

    
rjecnik_stemiranih_unigrama_treniranje={}
for recenica in recenice_stemiranih_unigrama_treniranje:
    for rijec in recenica:
        if rijec not in rjecnik_stemiranih_unigrama_treniranje:
            rjecnik_stemiranih_unigrama_treniranje[rijec]=1
        else:
            rjecnik_stemiranih_unigrama_treniranje[rijec]+=1
print(len(rjecnik_stemiranih_unigrama_treniranje))

for unigram in sorted(rjecnik_stemiranih_unigrama_treniranje.items(), key=lambda item: item[1], reverse=True):
    print(unigram)

16585
1833
('the', 859)
('to', 583)
('and', 456)
('hi', 436)
('he', 417)
('of', 338)
('wa', 317)
('that', 260)
('had', 257)
('it', 249)
('in', 240)
('a', 225)
('as', 178)
('would', 168)
('gregor', 165)
('him', 152)
('she', 140)
('not', 137)
('but', 135)
('with', 130)
('for', 127)
('at', 117)
('be', 116)
('her', 110)
('on', 107)
('have', 96)
('could', 95)
('all', 94)
('room', 92)
('from', 91)
('even', 90)
('there', 84)
('out', 82)
('they', 81)
('himself', 78)
('door', 78)
('been', 76)
('sister', 72)
('father', 70)
('thi', 69)
("gregor'", 69)
('now', 68)
('mother', 67)
('so', 66)
('if', 64)
('back', 60)
('time', 60)
('then', 59)
('up', 59)
('He', 58)
('did', 57)
('about', 55)
('more', 54)
('when', 52)
('into', 52)
('what', 51)
('were', 49)
('do', 48)
('than', 48)
('way', 46)
('onli', 45)
('one', 44)
('by', 44)
('no', 44)
('get', 43)
('open', 43)
('I', 42)
('you', 42)
('other', 41)
('ani', 39)
('them', 39)
('go', 39)
('littl', 37)
('chief', 37)
('just', 36)
('see', 35)
('look', 35)
('much

('opinion)', 1)
("everyone'", 1)
('permiss', 1)
('thu', 1)
('nowaday', 1)
('fanci', 1)
('underwear', 1)
('fashion', 1)
('sale', 1)
('shorthand', 1)
('french', 1)
('doze', 1)
('grin', 1)
('unus', 1)
('peg', 1)
('slumber', 1)
('serv', 1)
('superior', 1)
('result', 1)
('shabbier', 1)
('stain', 1)
('shini', 1)
('uncomfort', 1)
('obstin', 1)
('regularli', 1)
('importun', 1)
('tug', 1)
('sleev', 1)
('endear', 1)
('sink', 1)
('deeper', 1)
('abruptli', 1)
('support', 1)
('needl', 1)
('pen', 1)
('overwork', 1)
('household', 1)
('budget', 1)
('smaller', 1)
('thick-bon', 1)
('flap', 1)
('amount', 1)
('jewelleri', 1)
('belong', 1)
('sold', 1)
('function', 1)
('celebr', 1)
('loudest', 1)
('transfer', 1)
('address', 1)
('transport', 1)
('crate', 1)
('hole', 1)
('relat', 1)
('world', 1)
('poor', 1)
('sacrif', 1)
('behest', 1)
('custom', 1)
('dry-ey', 1)
("family'", 1)
('affair', 1)
('apprentic', 1)
('teaboy', 1)
('friend', 1)
('chambermaid', 1)
('provinci', 1)
('memori', 1)
('cashier', 1)
('whom', 1)

### Bigrami

Broj bigrama u korpusu je 16008, a broj različitih bigrama je 9678. Bigram koji se najviše puta pojavljuje je 'of the' i to 78 puta.

In [497]:
recenice_stemiranih_bigrama_treniranje=[]
recenica=[]
for i in recenice_stemiranih_unigrama_treniranje:
    for j in range(0,len(i)-1):
        recenica.append(i[j]+" "+i[j+1])
    recenice_stemiranih_bigrama_treniranje.append(recenica)
    recenica=[]
br=0
for i in recenice_stemiranih_bigrama_treniranje:
    for j in i:
        br=br+1
print(br)
    
rjecnik_stemiranih_bigrama_treniranje={}
for recenica in recenice_stemiranih_bigrama_treniranje:
    for rijec in recenica:
        if rijec not in rjecnik_stemiranih_bigrama_treniranje:
            rjecnik_stemiranih_bigrama_treniranje[rijec]=1
        else:
            rjecnik_stemiranih_bigrama_treniranje[rijec]+=1
print(len(rjecnik_stemiranih_bigrama_treniranje))

for bigram in sorted(rjecnik_stemiranih_bigrama_treniranje.items(), key=lambda item: item[1], reverse=True):
    print(bigram)

16008
9678
('of the', 78)
('he had', 68)
('the door', 63)
('in the', 58)
('hi father', 55)
('hi sister', 52)
('he wa', 51)
('it wa', 49)
('to the', 48)
('he could', 46)
('on the', 46)
('that he', 42)
('as he', 36)
('to be', 36)
('the chief', 36)
('of hi', 35)
('had been', 34)
('chief clerk', 34)
('from the', 33)
('in hi', 32)
('hi mother', 31)
('the room', 29)
('and the', 28)
('he would', 28)
('if he', 27)
('out of', 27)
('would have', 27)
('did not', 27)
('want to', 27)
('had to', 27)
('at the', 26)
('to do', 26)
('so that', 25)
('all the', 25)
('to get', 25)
('into the', 25)
('as if', 25)
('she had', 25)
('and he', 24)
('there wa', 24)
('the other', 24)
('have to', 23)
('when he', 23)
('hi head', 22)
('abl to', 22)
('wa not', 22)
('hi room', 21)
('to him', 21)
('a littl', 20)
('with the', 20)
('with hi', 20)
('to hi', 20)
('with a', 18)
('It wa', 18)
('open the', 18)
('on hi', 17)
('wa a', 17)
('that wa', 17)
('have been', 17)
('to see', 17)
('could not', 17)
('but he', 17)
('him to'

('the night', 2)
('end hi', 2)
('fulli dress', 2)
('not see', 2)
('him under', 2)
('control of', 2)
('herself and', 2)
('slam the', 2)
('door shut', 2)
('again from', 2)
('she seem', 2)
('she open', 2)
('away and', 2)
('and came', 2)
('in on', 2)
('a stranger', 2)
('right to', 2)
('she notic', 2)
('some other', 2)
('other food', 2)
('If she', 2)
('it herself', 2)
('would rather', 2)
('throw himself', 2)
('and beg', 2)
('her for', 2)
('sister notic', 2)
('the few', 2)
('it up', 2)
('day befor', 2)
('which had', 2)
('set asid', 2)
('asid for', 2)
('of consider', 2)
('feel as', 2)
('she knew', 2)
('more hi', 2)
('hi finger', 2)
('of how', 2)
('had still', 2)
('the chees', 2)
('him much', 2)
('food on', 2)
('after he', 2)
('eat and', 2)
('a sign', 2)
('in that', 2)
('them in', 2)
('close it', 2)
('gregor came', 2)
('hi food', 2)
('had eaten', 2)
('at midday', 2)
('would sleep', 2)
('send the', 2)
('and mother', 2)
('stand to', 2)
('have ani', 2)
('wa imposs', 2)
('imposs for', 2)
('even hi

('far across', 1)
('across that', 1)
('been hard', 1)
('hard for', 1)
('hi balanc', 1)
('balanc if', 1)
('he rock', 1)
('rock too', 1)
('now ten', 1)
('ten past', 1)
('seven and', 1)
('make a', 1)
('a final', 1)
('final decis', 1)
('decis veri', 1)
('a ring', 1)
('ring at', 1)
("that'll be", 1)
('be someon', 1)
('someon from', 1)
('and froze', 1)
('froze veri', 1)
('still although', 1)
('although hi', 1)
('leg onli', 1)
('onli becam', 1)
('becam all', 1)
('more live', 1)
('live as', 1)
('they danc', 1)
('danc around', 1)
('moment everyth', 1)
('everyth remain', 1)
('remain quiet', 1)
("they'r not", 1)
('himself caught', 1)
('caught in', 1)
('some nonsens', 1)
('nonsens hope', 1)
('then of', 1)
("the maid'", 1)
("maid' firm", 1)
('firm step', 1)
('step went', 1)
('went to', 1)
('as ever', 1)
('ever and', 1)
('and open', 1)
("the visitor'", 1)
("visitor' first", 1)
('of greet', 1)
('greet and', 1)
('knew who', 1)
('one condemn', 1)
('condemn to', 1)
('a compani', 1)
('compani where', 1)


('groundless complaint', 1)
('complaint and', 1)
("it' almost", 1)
('almost imposs', 1)
('imposs to', 1)
('to defend', 1)
('defend yourself', 1)
('yourself from', 1)
('that sort', 1)
('thing we', 1)
("we don't", 1)
("don't usual", 1)
('usual even', 1)
('even hear', 1)
('hear about', 1)
('about them', 1)
('them or', 1)
('if at', 1)
("all it'", 1)
("it' when", 1)
('we arriv', 1)
('arriv back', 1)
('back home', 1)
('home exhaust', 1)
('a trip', 1)
('trip and', 1)
("and that'", 1)
('we feel', 1)
('the harm', 1)
('harm effect', 1)
('effect of', 1)
("of what'", 1)
('been go', 1)
('on without', 1)
('what caus', 1)
('caus them', 1)
("don't go", 1)
('away at', 1)
('least first', 1)
('first say', 1)
('you grant', 1)
('grant that', 1)
("i'm at", 1)
('least partli', 1)
('partli right', 1)
('had turn', 1)
('turn away', 1)
('had start', 1)
('with protrud', 1)
('protrud lip', 1)
('lip onli', 1)
('onli stare', 1)
('stare back', 1)
('back at', 1)
('over hi', 1)
('hi trembl', 1)
('trembl shoulder', 1)
(

('first morn', 1)
('get them', 1)
('them out', 1)
('As nobodi', 1)
('nobodi could', 1)
('understand him', 1)
('him nobodi', 1)
('nobodi not', 1)
('sister thought', 1)
('understand them', 1)
('them so', 1)
('be content', 1)
('content to', 1)
("sister' sigh", 1)
('and appeal', 1)
('the saint', 1)
('saint as', 1)
('she move', 1)
('onli later', 1)
('later when', 1)
('becom a', 1)
('more use', 1)
('to everyth', 1)
('everyth there', 1)
('cours no', 1)
('no question', 1)
('question of', 1)
('her ever', 1)
('becom fulli', 1)
('fulli use', 1)
('the situat', 1)
('situat that', 1)
('sometim catch', 1)
('catch a', 1)
('a friendli', 1)
('friendli comment', 1)
('comment or', 1)
('a comment', 1)
('comment that', 1)
('be constru', 1)
('constru as', 1)
('as friendli', 1)
("he' enjoy", 1)
('enjoy hi', 1)
('hi dinner', 1)
('dinner today', 1)
('today she', 1)
('might say', 1)
('had dilig', 1)
('dilig clear', 1)
('clear away', 1)
('away all', 1)
('food left', 1)
('left for', 1)
('him or', 1)
('left most', 

('be as', 1)
('as care', 1)
('and consider', 1)
('consider as', 1)
('unfortun it', 1)
('who came', 1)
('back first', 1)
('first while', 1)
('while grete', 1)
('grete in', 1)
('room had', 1)
('had her', 1)
('arm round', 1)
('chest push', 1)
('push and', 1)
('pull at', 1)
('side by', 1)
('herself without', 1)
('without of', 1)
('cours move', 1)
('it an', 1)
('an inch', 1)
('not use', 1)
('might have', 1)
('her ill', 1)
('ill so', 1)
('so gregor', 1)
('gregor hurri', 1)
('backward to', 1)
('the far', 1)
('far end', 1)
('end of', 1)
('hi startlement', 1)
('startlement though', 1)
('not abl', 1)
('to prevent', 1)
('prevent the', 1)
('sheet at', 1)
('it front', 1)
('front from', 1)
('from move', 1)
('move a', 1)
('to attract', 1)
('attract hi', 1)
("mother' attent", 1)
('she stood', 1)
('stood veri', 1)
('still remain', 1)
('moment and', 1)
('then went', 1)
('back out', 1)
('to grete', 1)
('gregor kept', 1)
('kept tri', 1)
('to assur', 1)
('assur himself', 1)
('noth unusu', 1)
('unusu wa', 1

('look on', 1)
('on astonish', 1)
('and helpless', 1)
('helpless then', 1)
('then they', 1)
('they too', 1)
('too becam', 1)
('becam agit', 1)
("agit gregor'", 1)
('father stand', 1)
('right of', 1)
('mother accus', 1)
('accus her', 1)
('her of', 1)
('of not', 1)
('not leav', 1)
('the clean', 1)
('clean of', 1)
('sister from', 1)
('her left', 1)
("left gregor'", 1)
('sister scream', 1)
('scream at', 1)
('her that', 1)
('wa never', 1)
('to clean', 1)
("clean gregor'", 1)
('room again', 1)
('mother tri', 1)
('to draw', 1)
('draw hi', 1)
('father who', 1)
('wa besid', 1)
('with anger', 1)
('anger into', 1)
('the bedroom', 1)
('bedroom hi', 1)
('sister quak', 1)
('quak with', 1)
('with tear', 1)
('tear thump', 1)
('thump on', 1)
('her small', 1)
('small fist', 1)
('fist and', 1)
('gregor hiss', 1)
('hiss in', 1)
('in anger', 1)
('anger that', 1)
('and all', 1)
('all it', 1)
('it nois', 1)
('wa exhaust', 1)
('from go', 1)
('go out', 1)
('after gregor', 1)
('befor wa', 1)
('more work', 1)
('

### Trigrami

Broj trigrama u korpusu je 15439, a broj različitih trigrama je 13931. Trigram koji se najviše puta pojavljuje je 'the chief clerk' i to 33 puta.

In [498]:
recenice_stemiranih_trigrama_treniranje=[]
recenica=[]
for i in recenice_stemiranih_unigrama_treniranje:
    for j in range(0,len(i)-2):
        recenica.append(i[j]+" "+i[j+1]+" "+i[j+2])
    recenice_stemiranih_trigrama_treniranje.append(recenica)
    recenica=[]
br=0
for i in recenice_stemiranih_trigrama_treniranje:
    for j in i:
        br=br+1
print(br)
    
rjecnik_stemiranih_trigrama_treniranje={}
for recenica in recenice_stemiranih_trigrama_treniranje:
    for rijec in recenica:
        if rijec not in rjecnik_stemiranih_trigrama_treniranje:
            rjecnik_stemiranih_trigrama_treniranje[rijec]=1
        else:
            rjecnik_stemiranih_trigrama_treniranje[rijec]+=1
print(len(rjecnik_stemiranih_trigrama_treniranje))

for trigram in sorted(rjecnik_stemiranih_trigrama_treniranje.items(), key=lambda item: item[1], reverse=True):
    print(trigram)

15439
13931
('the chief clerk', 33)
('open the door', 14)
('out of the', 12)
('of hi bodi', 10)
('he had been', 10)
('that he had', 9)
('chest of drawer', 9)
('would have been', 9)
('the door and', 9)
('he had to', 9)
('the live room', 9)
('under the couch', 9)
('would have to', 8)
('he did not', 8)
('on the floor', 8)
('so that he', 7)
('that he could', 7)
('that it wa', 7)
('the chest of', 7)
('of the bed', 7)
('there wa a', 7)
('one of the', 7)
('the other side', 7)
('he want to', 7)
('he could not', 7)
('for him to', 7)
('as if he', 7)
('to the door', 7)
('to open the', 7)
('that he wa', 7)
('mother and sister', 7)
('where he wa', 6)
('that he would', 6)
('he would have', 6)
('said to himself', 6)
('when he had', 6)
('had to be', 6)
('in the even', 6)
('on the other', 6)
('and he wa', 6)
('of the door', 6)
('the next room', 6)
('into hi room', 6)
('in front of', 6)
('to hi father', 6)
('hi father would', 6)
('from under the', 6)
('and if he', 5)
('on the tabl', 5)
('on hi back', 5)

('disturb to get', 1)
('get dress and', 1)
('dress and most', 1)
('of all to', 1)
('all to have', 1)
('to have hi', 1)
('have hi breakfast', 1)
('then would he', 1)
('would he consid', 1)
('he consid what', 1)
('consid what to', 1)
('what to do', 1)
('to do next', 1)
('do next as', 1)
('next as he', 1)
('he wa well', 1)
('wa well awar', 1)
('would not bring', 1)
('not bring hi', 1)
('bring hi thought', 1)
('hi thought to', 1)
('thought to ani', 1)
('to ani sensibl', 1)
('ani sensibl conclus', 1)
('sensibl conclus by', 1)
('conclus by lie', 1)
('by lie in', 1)
('lie in bed', 1)
('He rememb that', 1)
('rememb that he', 1)
('he had often', 1)
('had often felt', 1)
('often felt a', 1)
('a slight pain', 1)
('slight pain in', 1)
('pain in bed', 1)
('in bed perhap', 1)
('bed perhap caus', 1)
('perhap caus by', 1)
('caus by lie', 1)
('by lie awkwardli', 1)
('lie awkwardli but', 1)
('awkwardli but that', 1)
('but that had', 1)
('that had alway', 1)
('had alway turn', 1)
('alway turn out', 1)
('

('leav him now', 1)
('him now in', 1)
('now in peac', 1)
('in peac instead', 1)
('peac instead of', 1)
('instead of disturb', 1)
('of disturb him', 1)
('disturb him with', 1)
('him with talk', 1)
('with talk at', 1)
('talk at him', 1)
('him and cri', 1)
('but the other', 1)
("the other didn't", 1)
("other didn't know", 1)
('know what wa', 1)
('what wa happen', 1)
('wa happen they', 1)
('happen they were', 1)
('they were worri', 1)
('were worri that', 1)
('worri that would', 1)
('that would excus', 1)
('would excus their', 1)
('excus their behaviour', 1)
('chief clerk now', 1)
('clerk now rais', 1)
('now rais hi', 1)
('hi voic mr.', 1)
('voic mr. samsa', 1)
('mr. samsa he', 1)
('samsa he call', 1)
('he call to', 1)
('to him what', 1)
('him what is', 1)
('what is wrong', 1)
('you barricad yourself', 1)
('barricad yourself in', 1)
('yourself in your', 1)
('in your room', 1)
('your room give', 1)
('room give us', 1)
('give us no', 1)
('us no more', 1)
('no more than', 1)
('more than ye', 1

('job be a', 1)
('be a commerci', 1)
('a commerci travel', 1)
('commerci travel is', 1)
('travel is arduou', 1)
('is arduou but', 1)
('arduou but without', 1)
('but without travel', 1)
('without travel I', 1)
("travel I couldn't", 1)
("I couldn't earn", 1)
("couldn't earn my", 1)
('earn my live', 1)
('So where are', 1)
('where are you', 1)
('are you go', 1)
('you go in', 1)
('go in to', 1)
('in to the', 1)
('to the offic', 1)
('will you report', 1)
('you report everyth', 1)
('report everyth accur', 1)
('everyth accur then', 1)
("it' quit possibl", 1)
('quit possibl for', 1)
('possibl for someon', 1)
('for someon to', 1)
('someon to be', 1)
('to be temporarili', 1)
('be temporarili unabl', 1)
('temporarili unabl to', 1)
('unabl to work', 1)
('to work but', 1)
("work but that'", 1)
("but that' just", 1)
("that' just the", 1)
('just the right', 1)
('the right time', 1)
('right time to', 1)
('time to rememb', 1)
("to rememb what'", 1)
("rememb what' been", 1)
("what' been achiev", 1)
('bee

('pain stretch scar', 1)
('stretch scar and', 1)
('scar and he', 1)
('and he limp', 1)
('he limp badli', 1)
('limp badli on', 1)
('badli on hi', 1)
('on hi two', 1)
('hi two row', 1)
('two row of', 1)
('row of leg', 1)
('of the leg', 1)
('the leg had', 1)
('leg had been', 1)
('had been badli', 1)
('been badli injur', 1)
('badli injur in', 1)
('injur in the', 1)
('in the event', 1)
('the event of', 1)
('event of that', 1)
('of that morn', 1)
('that morn it', 1)
('morn it wa', 1)
('it wa nearli', 1)
('wa nearli a', 1)
('nearli a miracl', 1)
('a miracl that', 1)
('miracl that onli', 1)
('that onli one', 1)
('onli one of', 1)
('of them had', 1)
('them had been', 1)
('had been and', 1)
('been and drag', 1)
('and drag along', 1)
('drag along lifelessli', 1)
('reach the door', 1)
('the door that', 1)
('door that he', 1)
('that he realis', 1)
('he realis what', 1)
('realis what it', 1)
('what it actual', 1)
('it actual wa', 1)
('actual wa that', 1)
('wa that had', 1)
('that had drawn', 1)
('ha

('should do now', 1)
('do now but', 1)
('now but even', 1)
('but even between', 1)
('even between meal', 1)
('between meal they', 1)
('meal they spoke', 1)
('they spoke about', 1)
('spoke about the', 1)
('about the same', 1)
('the same subject', 1)
('same subject as', 1)
('subject as there', 1)
('as there were', 1)
('there were alway', 1)
('were alway at', 1)
('alway at least', 1)
('at least two', 1)
('least two member', 1)
('two member of', 1)
('the famili at', 1)
('famili at home', 1)
('at home nobodi', 1)
('home nobodi want', 1)
('nobodi want to', 1)
('to be at', 1)
('be at home', 1)
('at home by', 1)
('home by themselv', 1)
('by themselv and', 1)
('themselv and it', 1)
('question to leav', 1)
('leav the flat', 1)
('the flat entir', 1)
('flat entir empti', 1)
('and on the', 1)
('on the veri', 1)
('the veri first', 1)
('veri first day', 1)
('first day the', 1)
('day the maid', 1)
('the maid had', 1)
('maid had fallen', 1)
('had fallen to', 1)
('fallen to her', 1)
('to her knee', 1)
(

('take it off', 1)
('it off again', 1)
('off again as', 1)
('again as it', 1)
('it wa clear', 1)
('wa clear enough', 1)
('clear enough that', 1)
('enough that it', 1)
('it wa no', 1)
('wa no pleasur', 1)
('no pleasur for', 1)
('pleasur for gregor', 1)
('gregor to cut', 1)
('to cut himself', 1)
('cut himself off', 1)
('himself off so', 1)
('off so complet', 1)
('she left the', 1)
('left the sheet', 1)
('the sheet where', 1)
('sheet where it', 1)
('gregor even thought', 1)
('even thought he', 1)
('thought he glimps', 1)
('he glimps a', 1)
('glimps a look', 1)
('a look of', 1)
('look of gratitud', 1)
('of gratitud one', 1)
('gratitud one time', 1)
('one time when', 1)
('when he care', 1)
('he care look', 1)
('care look out', 1)
('look out from', 1)
('the sheet to', 1)
('sheet to see', 1)
('to see how', 1)
('see how hi', 1)
('how hi sister', 1)
('sister like the', 1)
('like the new', 1)
('the new arrang', 1)
('the first fourteen', 1)
('first fourteen day', 1)
("fourteen day gregor'", 1)
("

('take now then', 1)
('said grete and', 1)
('grete and look', 1)
('and look around', 1)
('her eye met', 1)
('eye met those', 1)
('met those of', 1)
('those of gregor', 1)
('of gregor on', 1)
('perhap onli becaus', 1)
('onli becaus her', 1)
('becaus her mother', 1)
('her mother wa', 1)
('mother wa there', 1)
('wa there she', 1)
('there she remain', 1)
('she remain calm', 1)
('remain calm bent', 1)
('calm bent her', 1)
('bent her face', 1)
('her face to', 1)
('face to her', 1)
('to her so', 1)
('her so that', 1)
('she would not', 1)
('would not look', 1)
('not look round', 1)
('look round and', 1)
('round and said', 1)
('and said albeit', 1)
('said albeit hurriedli', 1)
('albeit hurriedli and', 1)
('hurriedli and with', 1)
('with a tremor', 1)
('a tremor in', 1)
('tremor in her', 1)
('in her voic', 1)
('her voic come', 1)
('voic come on', 1)
("come on let'", 1)
("on let' go", 1)
("let' go back", 1)
('go back in', 1)
('live room for', 1)
('could see what', 1)
('see what grete', 1)
('what 

('sleep in hi', 1)
('in hi chair', 1)
('hi chair hi', 1)
('chair hi mother', 1)
('hi mother and', 1)
('sister would urg', 1)
('would urg each', 1)
('urg each other', 1)
('each other to', 1)
('other to be', 1)
('to be quiet', 1)
('be quiet hi', 1)
('quiet hi mother', 1)
('hi mother bent', 1)
('mother bent deepli', 1)
('bent deepli under', 1)
('deepli under the', 1)
('under the lamp', 1)
('the lamp would', 1)
('lamp would sew', 1)
('would sew fanci', 1)
('sew fanci underwear', 1)
('fanci underwear for', 1)
('underwear for a', 1)
('for a fashion', 1)
('a fashion shop', 1)
('fashion shop hi', 1)
('shop hi sister', 1)
('sister who had', 1)
('who had taken', 1)
('had taken a', 1)
('taken a sale', 1)
('a sale job', 1)
('sale job learn', 1)
('job learn shorthand', 1)
('learn shorthand and', 1)
('shorthand and french', 1)
('and french in', 1)
('french in the', 1)
('the even so', 1)
('even so that', 1)
('that she might', 1)
('she might be', 1)
('might be abl', 1)
('to get a', 1)
('get a better',

# 2. Kneser-Ney metoda

Jedna od najčešće korištenih i najbolje izvedenih metoda za izglađivanje kod modeliranja jezika je Kneser-Ney metoda.
<br>Vjerojatnost pojavljivanja $w_i$ kao nastavka: $$P_{NASTAVAK}(w_i)=\frac{|\{w_{i-1}:c(w_{i-1},w_i)>0\}|}{|\{w_{j-1},w_j:c(w_{j-1},w_j)>0\}|}$$
Vjerojatnost unigrama: $$P_{KN}(w)=\frac{max(c_{KN}(w)-d,0)}{\sum_{w'}{c_{KN}(w')}}$$
Vjerojatnost bigrama: $$P_{KN}(w_i | w_{i-1})=\frac{max(c(w_{i-1}, w_i)-d,0)}{c(w_{i-1})}+\lambda(w_{i-1})P_{NASTAVAK}(w_i)$$
gdje je $$\lambda(w_{i-1})=\frac{d}{c(w_{i-1})}|\{w:c(w_{i-1},w)>0\}|$$
<br>Općenita rekurzivna relacija je $$P_{KN}(w_i | w_{i-n+1}^{i-1})=\frac{max(c_{KN}(w_{i-n+1}^i)-d,0)}{c_{KN}(w_{i-n+1}^{i-1})}+\lambda(w_{i-n+1}^{i-1})P_{KN}(w_i | w_{i-n+2}^{i-1})$$
S tim da je $c_{KN}(*)$ broj $(*)$ za veći red, a broj nastavka $(*)$, to jest broj jedinstvenih sadržaja s jednom riječju od * za manji red. 

## 2.1 Kneser-Ney metoda bez stemiranja

U ovom dijelu sam napisala funkcije za dobivanje vjerojatnosti unigrama, bigrama, trigrama, a i rečenica.

### Vjerojatnost nastavka

In [499]:
def vjerojatnost_nastavka(rijec):
    br=0
    for i in rjecnik_bigrama_treniranje:
        if i.split()[1]==rijec:
            br=br+1
    vjerojatnost=br/len(rjecnik_unigrama_treniranje)
    return vjerojatnost
vjerojatnost_nastavka('the')

0.09378960709759189

### Vjerojatnost unigrama

Kako je d fiksan, za unigrame sam koristila d=0.75.

In [500]:
def vjerojatnost_unigrama(rijec):
    if rijec in rjecnik_unigrama_treniranje:      
        vjerojatnost=max(rjecnik_unigrama_treniranje[rijec]-0.75,0)/len(rjecnik_unigrama_treniranje)
    else:
        vjerojatnost=0.75/len(rjecnik_unigrama_treniranje)
    return vjerojatnost
vjerojatnost_unigrama('the')

0.35076045627376423

### Vjerojatnost bigrama

Kako je d fiksan, za bigrame sam koristila d=0.75.

In [501]:
def vjerojatnost_bigrama(rijec):
    prva=rijec.split()[0]
    druga=rijec.split()[1]
    br=0
    br1=0
    for i in rjecnik_bigrama_treniranje:
        if i.split()[0]==prva:
            br=br+rjecnik_bigrama_treniranje[i]
            br1=br1+1
    br2=0
    for i in rjecnik_bigrama_treniranje:
        if i.split()[1]==druga:
            br2=br2+1
    if rijec in rjecnik_bigrama_treniranje:      
        vjerojatnost=max(rjecnik_bigrama_treniranje[rijec]-0.75,0)/br+(0.75/br)*br1*(br2/len(rjecnik_bigrama_treniranje))
    else:
        vjerojatnost=0.75/len(rjecnik_bigrama_treniranje)
    return vjerojatnost
vjerojatnost_bigrama('of the')

0.2351160570369432

### Vjerojatnost trigrama

U višim redovima n-grama, počevši od trigrama, koristimo d=0 pa je dovoljno izračunati $$\frac{c_{KN}(w_{i-n+1}^i)}{c_{KN}(w_{i-n+1}^{i-1})}$$

In [502]:
def vjerojatnost_trigrama(rijec):
    prva=rijec.split()[0]
    druga=rijec.split()[1]
    treca=rijec.split()[2]
    br=0
    for i in rjecnik_trigrama_treniranje:
        if i.split()[0]==prva and i.split()[1]==druga:
            br=br+rjecnik_trigrama_treniranje[i]
    if rijec in rjecnik_trigrama_treniranje:      
        vjerojatnost=rjecnik_trigrama_treniranje[rijec]/br
    else:
        vjerojatnost=0.75/len(rjecnik_trigrama_treniranje)
    return vjerojatnost
vjerojatnost_trigrama('the chief clerk')

0.9117647058823529

### Vjerojatnost rečenice

In [503]:
def vjerojatnost_recenice_unigrami(recenica):
    rijeci=recenica[:-1].split()
    vjerojatnost=1
    for i in range(0, len(rijeci)):
        vjerojatnost=vjerojatnost*vjerojatnost_unigrama(rijeci[i])
    return vjerojatnost
vjerojatnost_recenice_unigrami("The bedding was hardly able to cover it and seemed ready to slide off any moment.")

1.682017589252392e-34

In [504]:
def vjerojatnost_recenice_bigrami(recenica):
    rijeci=recenica[:-1].split()
    vjerojatnost=1
    for i in range(0, len(rijeci)-1):
        vjerojatnost=vjerojatnost*vjerojatnost_bigrama(rijeci[i]+" "+rijeci[i+1])
    return vjerojatnost
vjerojatnost_recenice_bigrami("The bedding was hardly able to cover it and seemed ready to slide off any moment.")

3.3317544261047286e-24

In [505]:
def vjerojatnost_recenice_trigrami(recenica):
    rijeci=recenica[:-1].split()
    vjerojatnost=1
    for i in range(0, len(rijeci)-2):
        vjerojatnost=vjerojatnost*vjerojatnost_trigrama(rijeci[i]+" "+rijeci[i+1]+" "+rijeci[i+2])
    return vjerojatnost
vjerojatnost_recenice_trigrami("The bedding was hardly able to cover it and seemed ready to slide off any moment.")

0.0004734848484848485

## 2.2 Kneser-Ney metoda sa stemiranjem

U ovom dijelu sam napisala funkcije za dobivanje vjerojatnosti unigrama, bigrama, trigrama, a i rečenica uz stemiranje.

### Vjerojatnost nastavka

In [506]:
def vjerojatnost_nastavka_stemirano(rijec):
    br=0
    for i in rjecnik_stemiranih_bigrama_treniranje:
        if i.split()[1]==rijec:
            br=br+1
    vjerojatnost=br/len(rjecnik_stemiranih_unigrama_treniranje)
    return vjerojatnost
vjerojatnost_nastavka_stemirano('the')

0.10638297872340426

### Vjerojatnost unigrama

Kako je d fiksan, za unigrame sam koristila d=0.75.

In [507]:
def vjerojatnost_stemiranih_unigrama(rijec):
    if rijec in rjecnik_stemiranih_unigrama_treniranje:
        vjerojatnost=max(rjecnik_stemiranih_unigrama_treniranje[rijec]-0.75,0)/len(rjecnik_stemiranih_unigrama_treniranje)
    else:
        vjerojatnost=0.75/len(rjecnik_stemiranih_unigrama_treniranje)
    return vjerojatnost
vjerojatnost_stemiranih_unigrama('the')

0.4682214948172395

### Vjerojatnost bigrama

Kako je d fiksan, za bigrame sam koristila d=0.75.

In [508]:
def vjerojatnost_stemiranih_bigrama(rijec):
    prva=rijec.split()[0]
    druga=rijec.split()[1]
    br=0
    br1=0
    for i in rjecnik_stemiranih_bigrama_treniranje:
        if i.split()[0]==prva:
            br=br+rjecnik_stemiranih_bigrama_treniranje[i]
            br1=br1+1
    br2=0
    for i in rjecnik_stemiranih_bigrama_treniranje:
        if i.split()[1]==druga:
            br2=br2+1
    if rijec in rjecnik_stemiranih_bigrama_treniranje:
        vjerojatnost=max(rjecnik_stemiranih_bigrama_treniranje[rijec]-0.75,0)/br+(0.75/br)*br1*(br2/len(rjecnik_stemiranih_bigrama_treniranje))
    else:
        vjerojatnost=0.75/len(rjecnik_stemiranih_bigrama_treniranje)
    return vjerojatnost
vjerojatnost_stemiranih_bigrama('of the')

0.2343852618101074

### Vjerojatnost trigrama

U višim redovima n-grama, počevši od trigrama, koristimo d=0 pa je dovoljno izračunati $$\frac{c_{KN}(w_{i-n+1}^i)}{c_{KN}(w_{i-n+1}^{i-1})}$$

In [509]:
def vjerojatnost_stemiranih_trigrama(rijec):
    prva=rijec.split()[0]
    druga=rijec.split()[1]
    treca=rijec.split()[2]
    br=0
    for i in rjecnik_stemiranih_trigrama_treniranje:
        if i.split()[0]==prva and i.split()[1]==druga:
            br=br+rjecnik_stemiranih_trigrama_treniranje[i]
    if rijec in rjecnik_stemiranih_trigrama_treniranje:      
        vjerojatnost=rjecnik_stemiranih_trigrama_treniranje[rijec]/br
    else:
        vjerojatnost=0.75/len(rjecnik_stemiranih_trigrama_treniranje)
    return vjerojatnost
vjerojatnost_stemiranih_trigrama('the chief clerk')

0.9166666666666666

### Vjerojatnost recenice

In [510]:
def vjerojatnost_recenice_stemirani_unigrami(recenica):
    rijeci=recenica[:-1].split()
    vjerojatnost=1
    for i in range(0, len(rijeci)):
        vjerojatnost=vjerojatnost*vjerojatnost_stemiranih_unigrama(rijeci[i])
    return vjerojatnost
vjerojatnost_recenice_stemirani_unigrami("The bedding was hardly able to cover it and seemed ready to slide off any moment.")

3.2652779019476986e-40

In [512]:
def vjerojatnost_recenice_stemirani_bigrami(recenica):
    rijeci=recenica[:-1].split()
    vjerojatnost=1
    for i in range(0, len(rijeci)-1):
        vjerojatnost=vjerojatnost*vjerojatnost_stemiranih_bigrama(rijeci[i]+" "+rijeci[i+1])
    return vjerojatnost
vjerojatnost_recenice_stemirani_bigrami("The bedding was hardly able to cover it and seemed ready to slide off any moment.")

4.686316277874896e-52

In [513]:
def vjerojatnost_recenice_stemirani_trigrami(recenica):
    rijeci=recenica[:-1].split()
    vjerojatnost=1
    for i in range(0, len(rijeci)-2):
        vjerojatnost=vjerojatnost*vjerojatnost_stemiranih_trigrama(rijeci[i]+" "+rijeci[i+1]+" "+rijeci[i+2])
    return vjerojatnost
vjerojatnost_recenice_stemirani_trigrami("The bedding was hardly able to cover it and seemed ready to slide off any moment.")

1.1012062886361362e-47

# 3. Perpleksija

Perpleksija je vjerojatnost testnog skupa normaliziranog po broju riječi 
$$PP(W)=P(w_1w_2...w_n)^{-\frac{1}{m}}$$
Zbog račala perpleksiju sam radila u logaritamskom prostoru:
$$10^{-\frac{1}{m}\sum_{i=1}^nlog_{10}P(w_i)}$$
W je korpus za testiranje, a $w_i$ je oznaka za i-tu rečenicu, i=1,...,n.
<br>m je oznaka za broj unigrama (bigrama, trigrama) u korpusu za testiranje.

In [515]:
recenice_unigrama_testiranje=[]
recenica=''
for i in range(0,len(korpus_za_testiranje)):
    if (korpus_za_testiranje[i]=='.' and korpus_za_testiranje[i-2:i]!="Mr" and korpus_za_testiranje[i-3:i]!="Mrs") or korpus_za_testiranje[i]=='!' or korpus_za_testiranje[i]=='?':
        recenice_unigrama_testiranje.append(recenica.split())
        recenica=''
    else:
        recenica=recenica+korpus_za_testiranje[i]

In [516]:
recenice_bigrama_testiranje=[]
recenica=[]
for i in recenice_unigrama_testiranje:
    for j in range(0,len(i)-1):
        recenica.append(i[j]+" "+i[j+1])
    recenice_bigrama_testiranje.append(recenica)
    recenica=[]

In [517]:
recenice_trigrama_testiranje=[]
recenica=[]
for i in recenice_unigrama_testiranje:
    for j in range(0,len(i)-2):
        recenica.append(i[j]+" "+i[j+1]+" "+i[j+2])
    recenice_trigrama_testiranje.append(recenica)
    recenica=[]

## 3.1 Bez stemiranja

### Unigrami

In [518]:
import math
perpleksija=0
br=0
recenica=""
for i in recenice_unigrama_testiranje:
    for j in i:
        recenica=recenica+j+" "
    recenica=recenica+"."
    if vjerojatnost_recenice_unigrami(recenica)>0:
        perpleksija=perpleksija+math.log(vjerojatnost_recenice_unigrami(recenica),10)
    br=br+len(i)
perpleksija=perpleksija*(-1/br)
perpleksija=math.pow(10, perpleksija)
print(perpleksija)

1.84557643261986


### Bigrami

In [442]:
import math
perpleksija=0
br=0
recenica=""
for i in recenice_unigrama_testiranje:
    for j in i:
        recenica=recenica+j+" "
    recenica=recenica+"."
    if vjerojatnost_recenice_bigrami(recenica)>0:
        perpleksija=perpleksija+math.log(vjerojatnost_recenice_bigrami(recenica),10)
    br=br+len(i)
perpleksija=perpleksija*(-1/(br-len(recenice_unigrama_testiranje)))
perpleksija=math.pow(10, perpleksija)
print(perpleksija)

KeyboardInterrupt: 

### Trigrami

In [359]:
import math
perpleksija=0
br=0
recenica=""
for i in recenice_unigrama_testiranje:
    for j in i:
        recenica=recenica+j+" "
    recenica=recenica+"."
    if vjerojatnost_recenice_trigrami(recenica)>0:
        perpleksija=perpleksija+math.log(vjerojatnost_recenice_trigrami(recenica),10)
    br=br+len(i)
perpleksija=perpleksija*(-1/(br-2*len(recenice_unigrama_testiranje)))
perpleksija=math.pow(10, perpleksija)
print(perpleksija)

KeyboardInterrupt: 

## 3.2. Sa stemiranjem

### Unigrami

In [519]:
import math
perpleksija=0
br=0
recenica=""
for i in recenice_unigrama_testiranje:
    for j in i:
        recenica=recenica+j+" "
    recenica=recenica+"."
    if vjerojatnost_recenice_stemirani_unigrami(recenica)>0:
        perpleksija=perpleksija+math.log(vjerojatnost_recenice_stemirani_unigrami(recenica),10)
    br=br+len(i)
perpleksija=perpleksija*(-1/br)
perpleksija=math.pow(10, perpleksija)
print(perpleksija)

1.8931854023212955


### Bigrami

In [444]:
import math
perpleksija=0
br=0
recenica=""
for i in recenice_unigrama_testiranje:
    for j in i:
        recenica=recenica+j+" "
    recenica=recenica+"."
    if vjerojatnost_recenice_stemirani_bigrami(recenica)>0:
        perpleksija=perpleksija+math.log(vjerojatnost_recenice_stemirani_bigrami(recenica),10)
    br=br+len(i)
perpleksija=perpleksija*(-1/(br-len(recenice_unigrama_testiranje)))
perpleksija=math.pow(10, perpleksija)
print(perpleksija)

KeyboardInterrupt: 

### Trigrami

In [520]:
import math
perpleksija=0
br=0
recenica=""
for i in recenice_unigrama_testiranje:
    for j in i:
        recenica=recenica+j+" "
    recenica=recenica+"."
    if vjerojatnost_recenice_stemirani_trigrami(recenica)>0:
        perpleksija=perpleksija+math.log(vjerojatnost_recenice_stemirani_trigrami(recenica),10)
    br=br+len(i)
perpleksija=perpleksija*(-1/(br-2*len(recenice_unigrama_testiranje)))
perpleksija=math.pow(10, perpleksija)
print(perpleksija)

KeyboardInterrupt: 

# 4. Zaključak

Perpleksija kod unigrama bez stemiranja: 1.84557643261986
<br>Perpleksija kod unigrama uz stemiranje: 1.8931854023212955
<br>Kako je perpleksija manja kod unigrama bez stemiranja, zaključujem da je taj model bolji od modela unigrama sa stemiranjem.